// Lesson content for three practical courses (trilingual: kw · fr · en).
// Each lesson: { id, sec, icon, title, lesson, analogy, example, money{kw,fr,en[]}, quiz{kw,fr,en{q,a[],c}} }

// ============== APRAN ITILIZE CHATGPT ==============
window.KAH_CHATGPT = [
  { id:1, sec:'Kòmanse ak ChatGPT', icon:'💬',
    title:{kw:'Ki sa ChatGPT ye?',fr:"Qu'est-ce que ChatGPT ?",en:'What is ChatGPT?'},
    lesson:{kw:'ChatGPT se yon asistan AI ki konprann tèks epi reponn ou an lang natirèl. Ou ka mande l ekri, eksplike, rezime, oswa ede w rezoud pwoblèm.',fr:"ChatGPT est un assistant IA qui comprend le texte et répond en langage naturel. Vous pouvez lui demander d'écrire, d'expliquer, de résumer ou de résoudre des problèmes.",en:'ChatGPT is an AI assistant that understands text and answers in natural language. You can ask it to write, explain, summarize, or help solve problems.'},
    analogy:{kw:"Tankou yon asistan entelijan ki disponib 24/7 — ou pale avè l menm jan ou tape yon mesaj WhatsApp.",fr:"Comme un assistant intelligent disponible 24/7 — vous lui parlez comme un message WhatsApp.",en:"Like a smart assistant available 24/7 — you talk to it just like texting on WhatsApp."},
    example:{kw:"Yon etidyan nan Pòtoprens itilize ChatGPT pou eksplike yon leson matematik li pa t konprann — gratis, nan 2 minit.",fr:"Un étudiant à Port-au-Prince utilise ChatGPT pour expliquer une leçon de maths — gratuit, en 2 minutes.",en:"A student in Port-au-Prince uses ChatGPT to explain a math lesson he didn't understand — free, in 2 minutes."},
    money:{kw:['Sèvis redaksyon CV $10-30','Ede elèv ak devwa','Tradui dokiman'],fr:['Service de rédaction de CV 10-30 $',"Aide aux devoirs",'Traduire des documents'],en:['CV writing service $10-30','Help students with homework','Translate documents']},
    quiz:{kw:{q:'Ki sa ChatGPT ye?',a:['Yon jwèt videyo','Yon asistan AI ki reponn an lang natirèl','Yon rezo sosyal','Yon bank'],c:1},
          fr:{q:"Qu'est-ce que ChatGPT ?",a:['Un jeu vidéo','Un assistant IA qui répond en langage naturel','Un réseau social','Une banque'],c:1},
          en:{q:'What is ChatGPT?',a:['A video game','An AI assistant that answers in natural language','A social network','A bank'],c:1}} },
  { id:2, sec:'Kòmanse ak ChatGPT', icon:'🔑',
    title:{kw:'Kreye kont + premye konvèsasyon',fr:'Créer un compte + première conversation',en:'Create an account + first chat'},
    lesson:{kw:'Ale sou chat.openai.com, enskri ak imèl ou (gratis). Tape kesyon ou nan bwat la epi peze Enter. Ou ka kontinye konvèsasyon an pou rafine repons lan.',fr:"Allez sur chat.openai.com, inscrivez-vous avec votre e-mail (gratuit). Tapez votre question et appuyez sur Entrée. Continuez la conversation pour affiner la réponse.",en:'Go to chat.openai.com, sign up with your email (free). Type your question and press Enter. Keep the conversation going to refine the answer.'},
    analogy:{kw:"Tankou louvri yon nouvo chat WhatsApp — men moun nan lòt bò a se yon AI ki konnen anpil bagay.",fr:"Comme ouvrir un nouveau chat WhatsApp — mais en face, c'est une IA qui sait beaucoup de choses.",en:"Like opening a new WhatsApp chat — but on the other side is an AI that knows a lot."},
    example:{kw:"Marie kreye kont li epi mande: « Ekri yon mesaj pou ranmase kòb nan men kliyan an reta » — li jwenn yon bon brouyon nan segond.",fr:"Marie crée son compte et demande : « Écris un message pour relancer un client en retard » — un bon brouillon en quelques secondes.",en:"Marie creates her account and asks: “Write a message to collect payment from a late client” — a solid draft in seconds."},
    money:{kw:["Vann sèvis « asistan vityèl »",'Reponn mesaj kliyan pi vit'],fr:['Vendre un service « assistant virtuel »','Répondre aux clients plus vite'],en:['Sell a “virtual assistant” service','Answer client messages faster']},
    quiz:{kw:{q:'Ki kote ou ale pou itilize ChatGPT?',a:['chat.openai.com','facebook.com','Google Maps','yon ATM'],c:0},
          fr:{q:'Où allez-vous pour utiliser ChatGPT ?',a:['chat.openai.com','facebook.com','Google Maps','un distributeur'],c:0},
          en:{q:'Where do you go to use ChatGPT?',a:['chat.openai.com','facebook.com','Google Maps','an ATM'],c:0}} },
  { id:3, sec:'Kòmanse ak ChatGPT', icon:'🎯',
    title:{kw:'Kijan poze bon kesyon',fr:'Comment poser de bonnes questions',en:'How to ask good questions'},
    lesson:{kw:'Plis ou klè, pi bon repons lan. Di AI a kiyès li ye (wòl), sa ou vle (objektif), ak kontèks la. Bay egzanp si w kapab.',fr:"Plus vous êtes clair, meilleure est la réponse. Dites à l'IA son rôle, votre objectif et le contexte. Donnez un exemple si possible.",en:'The clearer you are, the better the answer. Tell the AI its role, your goal, and the context. Give an example if you can.'},
    analogy:{kw:"Tankou bay yon zanmi enstriksyon: « ban m yon plan » flou; « ban m yon plan 7 jou pou vann diri sou Facebook » klè.",fr:"Comme donner des consignes à un ami : « donne-moi un plan » est vague ; « un plan de 7 jours pour vendre du riz sur Facebook » est clair.",en:"Like instructing a friend: “give me a plan” is vague; “a 7-day plan to sell rice on Facebook” is clear."},
    example:{kw:"Olye « ekri yon post », di: « Ekri yon post Facebook 100 mo pou yon machann rad nan Dèlma, ton zanmitay, ak yon apèl pou aksyon. »",fr:"Au lieu de « écris un post », dites : « Écris un post Facebook de 100 mots pour une vendeuse de vêtements à Delmas, ton amical, avec un appel à l'action. »",en:"Instead of “write a post,” say: “Write a 100-word Facebook post for a clothing seller in Delmas, friendly tone, with a call to action.”"},
    money:{kw:['Pi bon prompt = pi bon kontni = plis kliyan','Vann sèvis kreyasyon kontni'],fr:['Meilleur prompt = meilleur contenu = plus de clients','Vendre un service de création de contenu'],en:['Better prompt = better content = more clients','Sell a content-creation service']},
    quiz:{kw:{q:'Ki sa ki fè yon bon kesyon pou ChatGPT?',a:['Kenbe l vag','Bay wòl, objektif ak kontèks klè','Ekri an majiskil','Poze l yon sèl mo'],c:1},
          fr:{q:'Qu\'est-ce qui fait une bonne question pour ChatGPT ?',a:['Rester vague','Donner rôle, objectif et contexte clairs','Écrire en majuscules','Un seul mot'],c:1},
          en:{q:'What makes a good ChatGPT question?',a:['Keep it vague','Give clear role, goal and context','Write in all caps','Just one word'],c:1}} },
  { id:4, sec:'Itilize ak Fè Lajan', icon:'🗂️',
    title:{kw:'ChatGPT pou travay chak jou',fr:'ChatGPT au quotidien',en:'ChatGPT for daily work'},
    lesson:{kw:'ChatGPT ka ede w ekri imèl, fè CV, planifye semèn ou, rezime dokiman long, oswa jenere lide. Itilize l kòm yon patnè travay.',fr:"ChatGPT peut écrire des e-mails, faire un CV, planifier votre semaine, résumer de longs documents ou générer des idées. Un vrai partenaire de travail.",en:'ChatGPT can write emails, build a CV, plan your week, summarize long documents, or generate ideas. Use it as a work partner.'},
    analogy:{kw:"Tankou gen yon sekretè ki pa janm fatige — li fè premye brouyon an, ou rafine l.",fr:"Comme une secrétaire infatigable — elle fait le premier brouillon, vous l'affinez.",en:"Like a secretary who never gets tired — it makes the first draft, you refine it."},
    example:{kw:"Yon antreprenè rezime yon kontra 10 paj an 5 pwen ak ChatGPT anvan li siyen.",fr:"Un entrepreneur résume un contrat de 10 pages en 5 points avec ChatGPT avant de signer.",en:"An entrepreneur summarizes a 10-page contract into 5 points with ChatGPT before signing."},
    money:{kw:['Sèvis administratif','Ekri pwopozisyon biznis','Plan biznis pou kliyan'],fr:['Services administratifs','Rédiger des propositions commerciales','Plans d\'affaires pour clients'],en:['Admin services','Write business proposals','Business plans for clients']},
    quiz:{kw:{q:'Ki travay ChatGPT PA ka fè?',a:['Ekri imèl','Rezime dokiman','Pote yon kafe ba ou fizikman','Fè yon CV'],c:2},
          fr:{q:'Quelle tâche ChatGPT NE peut PAS faire ?',a:['Écrire un e-mail','Résumer un document','Vous apporter un café physiquement','Faire un CV'],c:2},
          en:{q:'Which task can ChatGPT NOT do?',a:['Write an email','Summarize a document','Physically bring you a coffee','Make a CV'],c:2}} },
  { id:5, sec:'Itilize ak Fè Lajan', icon:'⚠️',
    title:{kw:'Limit ak verifye enfòmasyon',fr:'Limites et vérification',en:'Limits and verifying info'},
    lesson:{kw:'ChatGPT ka fè erè oswa envante enfòmasyon (« halusinasyon »). Toujou verifye fè enpòtan, dat, ak sitasyon anvan ou itilize yo.',fr:"ChatGPT peut se tromper ou inventer (« hallucination »). Vérifiez toujours les faits importants, dates et citations avant de les utiliser.",en:"ChatGPT can make mistakes or invent facts (“hallucination”). Always verify important facts, dates, and quotes before using them."},
    analogy:{kw:"Tankou yon zanmi ki konnen anpil bagay men ki ka twonpe l pafwa — fè konfyans, men verifye.",fr:"Comme un ami très savant qui se trompe parfois — faites confiance, mais vérifiez.",en:"Like a very knowledgeable friend who's sometimes wrong — trust, but verify."},
    example:{kw:"Yon jounalis itilize ChatGPT pou brouyon, men li verifye chak non ak chif nan sous ofisyèl.",fr:"Un journaliste utilise ChatGPT pour le brouillon, mais vérifie chaque nom et chiffre dans des sources officielles.",en:"A journalist uses ChatGPT for a draft but checks every name and number against official sources."},
    money:{kw:['Sèvis ki gen kalite = repitasyon','Evite erè ki ka koute kliyan'],fr:['Un service de qualité = réputation','Éviter des erreurs coûteuses'],en:['Quality service = reputation','Avoid mistakes that cost clients']},
    quiz:{kw:{q:'Sa ou dwe fè ak enfòmasyon ChatGPT bay?',a:['Kwè tout san kesyon','Verifye fè enpòtan yo','Pa janm itilize l','Efase l'],c:1},
          fr:{q:'Que faire des infos données par ChatGPT ?',a:['Tout croire sans question','Vérifier les faits importants','Ne jamais l\'utiliser','Les effacer'],c:1},
          en:{q:'What should you do with info ChatGPT gives?',a:['Believe it all','Verify the important facts','Never use it','Delete it'],c:1}} },
  { id:6, sec:'Itilize ak Fè Lajan', icon:'💰',
    title:{kw:'Fè lajan ak ChatGPT',fr:'Gagner de l\'argent avec ChatGPT',en:'Make money with ChatGPT'},
    lesson:{kw:'Ofri sèvis: redaksyon, tradiksyon, kontni rezo sosyal, asistan vityèl, oswa kreye pwodwi dijital (e-book, gid). Konbine konpetans ou ak vitès AI.',fr:"Offrez des services : rédaction, traduction, contenu réseaux sociaux, assistant virtuel, ou produits numériques (e-book, guides). Combinez vos compétences à la vitesse de l'IA.",en:'Offer services: writing, translation, social-media content, virtual assistant, or digital products (e-books, guides). Combine your skills with AI speed.'},
    analogy:{kw:"ChatGPT se zouti a; ou se atizan an. Valè ou ofri = lajan ou touche.",fr:"ChatGPT est l'outil ; vous êtes l'artisan. La valeur que vous offrez = ce que vous gagnez.",en:"ChatGPT is the tool; you're the craftsman. The value you offer = what you earn."},
    example:{kw:"Jean ofri « jesyon paj Facebook ak AI » a 5 ti biznis nan zòn li — $50/mwa chak = $250/mwa.",fr:"Jean propose « gestion de page Facebook avec IA » à 5 petites entreprises — 50 $/mois chacune = 250 $/mois.",en:"Jean offers “Facebook page management with AI” to 5 small businesses — $50/mo each = $250/mo."},
    money:{kw:['Asistan vityèl $100-300/mwa','Kreye e-book pou vann','Sèvis kontni rezo sosyal','Tradiksyon ak redaksyon'],fr:['Assistant virtuel 100-300 $/mois','Créer des e-books à vendre','Service de contenu social','Traduction et rédaction'],en:['Virtual assistant $100-300/mo','Create e-books to sell','Social-media content service','Translation and writing']},
    quiz:{kw:{q:'Ki jan ou fè lajan ak ChatGPT?',a:['Tann li voye w kòb','Ofri sèvis ki konbine konpetans ou ak AI','Pataje modpas ou','Anyen posib'],c:1},
          fr:{q:'Comment gagner de l\'argent avec ChatGPT ?',a:['Attendre qu\'il vous envoie de l\'argent','Offrir des services qui allient vos compétences et l\'IA','Partager votre mot de passe','Rien n\'est possible'],c:1},
          en:{q:'How do you make money with ChatGPT?',a:['Wait for it to send you money','Offer services combining your skills with AI','Share your password','Nothing is possible'],c:1}} }
];

// ============== APRAN ITILIZE CLAUDE ==============
window.KAH_CLAUDE = [
  { id:1, sec:'Kòmanse ak Claude', icon:'🤖',
    title:{kw:'Ki sa Claude ye?',fr:"Qu'est-ce que Claude ?",en:'What is Claude?'},
    lesson:{kw:'Claude se yon asistan AI Anthropic kreye. Li bon anpil pou ekriti, analiz, ak travay ak dokiman long. Li bay repons ki reflechi epi an sekirite.',fr:"Claude est un assistant IA créé par Anthropic. Il excelle en rédaction, analyse et traitement de longs documents. Ses réponses sont réfléchies et sûres.",en:'Claude is an AI assistant created by Anthropic. It excels at writing, analysis, and working with long documents. Its answers are thoughtful and safe.'},
    analogy:{kw:"Si ChatGPT se yon kouto swis, Claude se yon plim ekriven — li briye nan tèks long ak rezònman.",fr:"Si ChatGPT est un couteau suisse, Claude est une plume d'écrivain — il brille dans les longs textes et le raisonnement.",en:"If ChatGPT is a Swiss army knife, Claude is a writer's pen — it shines at long text and reasoning."},
    example:{kw:"Yon etidyan inivèsite mete yon atik 30 paj nan Claude epi mande l rezime ak kritike agiman yo.",fr:"Un étudiant met un article de 30 pages dans Claude et lui demande de résumer et critiquer les arguments.",en:"A university student drops a 30-page article into Claude and asks it to summarize and critique the arguments."},
    money:{kw:['Analiz dokiman pou pwofesyonèl','Ekriti long (rapò, atik)','Rezime akademik'],fr:['Analyse de documents pour pros','Rédaction longue (rapports, articles)','Résumés académiques'],en:['Document analysis for pros','Long-form writing (reports, articles)','Academic summaries']},
    quiz:{kw:{q:'Kiyès ki kreye Claude?',a:['Google','Anthropic','Meta','Apple'],c:1},
          fr:{q:'Qui a créé Claude ?',a:['Google','Anthropic','Meta','Apple'],c:1},
          en:{q:'Who created Claude?',a:['Google','Anthropic','Meta','Apple'],c:1}} },
  { id:2, sec:'Kòmanse ak Claude', icon:'🔑',
    title:{kw:'Kreye kont + entèfas la',fr:'Créer un compte + l\'interface',en:'Create an account + the interface'},
    lesson:{kw:'Ale sou claude.ai, enskri gratis. Entèfas la senp: tape mesaj ou, atache dokiman (PDF, tèks) epi Claude analize yo.',fr:"Allez sur claude.ai, inscrivez-vous gratuitement. Interface simple : tapez votre message, joignez des documents (PDF, texte) et Claude les analyse.",en:'Go to claude.ai, sign up free. The interface is simple: type your message, attach documents (PDF, text), and Claude analyzes them.'},
    analogy:{kw:"Tankou bay yon konseye yon dosye konplè — li li tout anvan li reponn ou.",fr:"Comme remettre un dossier complet à un conseiller — il lit tout avant de répondre.",en:"Like handing a full file to an advisor — it reads everything before answering."},
    example:{kw:"Marie atache yon kontra epi mande Claude: « Ki risk ki genyen pou mwen nan kontra sa? »",fr:"Marie joint un contrat et demande à Claude : « Quels risques ce contrat présente-t-il pour moi ? »",en:"Marie attaches a contract and asks Claude: “What risks does this contract pose for me?”"},
    money:{kw:['Sèvis revize kontra','Analiz dokiman biznis'],fr:['Service de révision de contrats','Analyse de documents d\'affaires'],en:['Contract review service','Business document analysis']},
    quiz:{kw:{q:'Ki sit ou itilize pou Claude?',a:['claude.ai','openai.com','bing.com','x.com'],c:0},
          fr:{q:'Quel site pour utiliser Claude ?',a:['claude.ai','openai.com','bing.com','x.com'],c:0},
          en:{q:'Which site do you use for Claude?',a:['claude.ai','openai.com','bing.com','x.com'],c:0}} },
  { id:3, sec:'Kòmanse ak Claude', icon:'📚',
    title:{kw:'Travay ak dokiman long',fr:'Travailler avec de longs documents',en:'Working with long documents'},
    lesson:{kw:'Claude ka li anpil paj nan yon sèl kou. Itilize l pou rezime, konpare, oswa jwenn enfòmasyon nan gwo dokiman.',fr:"Claude peut lire de nombreuses pages d'un coup. Utilisez-le pour résumer, comparer ou retrouver des infos dans de gros documents.",en:'Claude can read many pages at once. Use it to summarize, compare, or find information inside large documents.'},
    analogy:{kw:"Tankou yon bibliyotekè ki li tout liv la pou ou epi di w kote repons lan ye.",fr:"Comme un bibliothécaire qui lit tout le livre pour vous et vous indique où est la réponse.",en:"Like a librarian who reads the whole book for you and points to where the answer is."},
    example:{kw:"Yon avoka mete 50 paj temwayaj epi mande Claude jwenn tout kontradiksyon yo.",fr:"Un avocat met 50 pages de témoignages et demande à Claude de trouver toutes les contradictions.",en:"A lawyer pastes 50 pages of testimony and asks Claude to find all the contradictions."},
    money:{kw:['Rechèch ak rezime pou kliyan','Analiz rapò long'],fr:['Recherche et résumé pour clients','Analyse de longs rapports'],en:['Research & summaries for clients','Analysis of long reports']},
    quiz:{kw:{q:'Nan ki Claude espesyalman fò?',a:['Jwe mizik','Travay ak dokiman long','Voye SMS','Pran foto'],c:1},
          fr:{q:'En quoi Claude est-il particulièrement fort ?',a:['Jouer de la musique','Traiter de longs documents','Envoyer des SMS','Prendre des photos'],c:1},
          en:{q:'What is Claude especially strong at?',a:['Playing music','Working with long documents','Sending texts','Taking photos'],c:1}} },
  { id:4, sec:'Pwofesyonèl ak Claude', icon:'✍️',
    title:{kw:'Claude pou analiz ak ekriti',fr:'Claude pour l\'analyse et l\'écriture',en:'Claude for analysis and writing'},
    lesson:{kw:'Claude bay tèks ki klè ak byen estriktire. Itilize l pou atik, esè, imèl pwofesyonèl, oswa analiz done.',fr:"Claude produit un texte clair et bien structuré. Utilisez-le pour articles, essais, e-mails pros ou analyse de données.",en:'Claude produces clear, well-structured text. Use it for articles, essays, professional emails, or data analysis.'},
    analogy:{kw:"Tankou yon korektè ak yon ekriven ansanm — li ede w di sa ou vle di pi byen.",fr:"Comme un correcteur et un écrivain réunis — il vous aide à mieux dire ce que vous voulez dire.",en:"Like an editor and a writer in one — it helps you say what you mean, better."},
    example:{kw:"Yon kreyatè kontni ekri yon nouvèl atik chak semèn ak Claude epi double pwodiksyon l.",fr:"Un créateur de contenu écrit un nouvel article chaque semaine avec Claude et double sa production.",en:"A content creator writes a new article each week with Claude and doubles their output."},
    money:{kw:['Sèvis redaksyon pwofesyonèl','Gòst-ekriti (ghostwriting)','Newsletter pou biznis'],fr:['Service de rédaction pro','Ghostwriting','Newsletters pour entreprises'],en:['Professional writing service','Ghostwriting','Newsletters for businesses']},
    quiz:{kw:{q:'Pou ki sa Claude bon?',a:['Tèks klè ak analiz','Kondui machin','Kwit manje','Voye lajan'],c:0},
          fr:{q:'À quoi Claude est-il bon ?',a:['Texte clair et analyse','Conduire','Cuisiner','Envoyer de l\'argent'],c:0},
          en:{q:'What is Claude good at?',a:['Clear text & analysis','Driving','Cooking','Sending money'],c:0}} },
  { id:5, sec:'Pwofesyonèl ak Claude', icon:'🛡️',
    title:{kw:'Sekirite ak bon jan repons',fr:'Sécurité et réponses fiables',en:'Safety and reliable answers'},
    lesson:{kw:'Claude fèt pou bay repons ki itil, onèt, ak san danje. Men menm jan ak tout AI, verifye fè enpòtan yo.',fr:"Claude est conçu pour des réponses utiles, honnêtes et sûres. Mais comme toute IA, vérifiez les faits importants.",en:'Claude is built to be helpful, honest, and harmless. But like any AI, verify important facts.'},
    analogy:{kw:"Tankou yon konseye pridan — li p ap ba w move konsèy fasil, men ou toujou gen dènye mo a.",fr:"Comme un conseiller prudent — il ne donne pas de mauvais conseils à la légère, mais le dernier mot vous revient.",en:"Like a careful advisor — it won't give bad advice lightly, but you always have the final word."},
    example:{kw:"Yon pwofesè itilize Claude pou prepare leson, men li verifye dat istorik yo.",fr:"Un professeur prépare ses cours avec Claude mais vérifie les dates historiques.",en:"A teacher uses Claude to prepare lessons but double-checks the historical dates."},
    money:{kw:['Kalite ak konfyans = plis kliyan','Sèvis edikatif'],fr:['Qualité et confiance = plus de clients','Services éducatifs'],en:['Quality & trust = more clients','Educational services']},
    quiz:{kw:{q:'Ki prensip ki gide Claude?',a:['Itil, onèt, san danje','Pi vit posib sèlman','Pi dwòl posib','Anyen'],c:0},
          fr:{q:'Quels principes guident Claude ?',a:['Utile, honnête, sûr','Le plus rapide seulement','Le plus drôle','Aucun'],c:0},
          en:{q:'What principles guide Claude?',a:['Helpful, honest, harmless','Fastest only','Funniest','None'],c:0}} },
  { id:6, sec:'Pwofesyonèl ak Claude', icon:'💰',
    title:{kw:'Fè lajan ak Claude',fr:'Gagner de l\'argent avec Claude',en:'Make money with Claude'},
    lesson:{kw:'Ofri sèvis ki mande ekriti ak analiz fen: rapò, atik, revize dokiman, rechèch. Claude bay yon avantaj kalite.',fr:"Offrez des services exigeant écriture et analyse fines : rapports, articles, révision de documents, recherche. Claude donne un avantage qualité.",en:'Offer services that need fine writing and analysis: reports, articles, document review, research. Claude gives a quality edge.'},
    analogy:{kw:"Claude se patnè ekriti w; ou vann rezilta a, pa zouti a.",fr:"Claude est votre partenaire d'écriture ; vous vendez le résultat, pas l'outil.",en:"Claude is your writing partner; you sell the result, not the tool."},
    example:{kw:"Pòl ofri « analiz ak rezime dokiman » a biznis lokal — $40 pa dokiman.",fr:"Paul propose « analyse et résumé de documents » aux entreprises locales — 40 $ par document.",en:"Paul offers “document analysis & summary” to local businesses — $40 per document."},
    money:{kw:['Redaksyon pwofesyonèl $20-100','Analiz dokiman','Gòst-ekriti','Rechèch pou kliyan'],fr:['Rédaction pro 20-100 $','Analyse de documents','Ghostwriting','Recherche pour clients'],en:['Professional writing $20-100','Document analysis','Ghostwriting','Research for clients']},
    quiz:{kw:{q:'Kijan Claude ede w fè lajan?',a:['Sèvis ekriti ak analiz kalite','Li voye w kòb','Li jwe lotri','Pa posib'],c:0},
          fr:{q:'Comment Claude aide-t-il à gagner de l\'argent ?',a:['Services d\'écriture et d\'analyse de qualité','Il vous envoie de l\'argent','Il joue au loto','Impossible'],c:0},
          en:{q:'How does Claude help you make money?',a:['Quality writing & analysis services','It sends you money','It plays the lottery','Not possible'],c:0}} }
];

// ============== APRAN EKRI BON PROMPT ==============
window.KAH_PROMPT = [
  { id:1, sec:'Baz Prompt', icon:'⌨️',
    title:{kw:'Ki sa yon prompt ye?',fr:"Qu'est-ce qu'un prompt ?",en:'What is a prompt?'},
    lesson:{kw:'Yon prompt se enstriksyon ou bay yon AI. Pi bon prompt lan, pi bon rezilta a. Se konpetans #1 pou metrize AI.',fr:"Un prompt est l'instruction que vous donnez à une IA. Meilleur est le prompt, meilleur est le résultat. C'est LA compétence n°1 pour maîtriser l'IA.",en:'A prompt is the instruction you give an AI. The better the prompt, the better the result. It is the #1 skill for mastering AI.'},
    analogy:{kw:"Tankou yon resèt: si enstriksyon yo klè, manje a bon; si yo flou, rezilta a flou.",fr:"Comme une recette : instructions claires, bon plat ; instructions floues, résultat flou.",en:"Like a recipe: clear instructions, good dish; vague instructions, vague result."},
    example:{kw:"Menm AI a bay yon move repons ak « ekri yon bagay », men yon bon repons ak yon prompt detaye.",fr:"La même IA donne une mauvaise réponse avec « écris un truc », mais une bonne avec un prompt détaillé.",en:"The same AI gives a poor answer to “write something,” but a great one to a detailed prompt."},
    money:{kw:['Bon prompt = bon kontni = plis kliyan',"Vann « prompt packs »"],fr:['Bon prompt = bon contenu = plus de clients','Vendre des « prompt packs »'],en:['Good prompt = good content = more clients','Sell “prompt packs”']},
    quiz:{kw:{q:'Ki sa yon prompt ye?',a:['Enstriksyon ou bay AI','Yon kalite òdinatè','Yon viris','Yon paj web'],c:0},
          fr:{q:"Qu'est-ce qu'un prompt ?",a:['L\'instruction donnée à l\'IA','Un type d\'ordinateur','Un virus','Une page web'],c:0},
          en:{q:'What is a prompt?',a:['The instruction you give an AI','A type of computer','A virus','A web page'],c:0}} },
  { id:2, sec:'Baz Prompt', icon:'🧩',
    title:{kw:'Fòmil la: Wòl + Objektif + Kontèks',fr:'La formule : Rôle + Objectif + Contexte',en:'The formula: Role + Goal + Context'},
    lesson:{kw:'Yon bon prompt gen 3 pati: Wòl (kiyès AI a ye), Objektif (sa ou vle), Kontèks (detay ak kontrent). Sa bay rezilta pafè.',fr:"Un bon prompt a 3 parties : Rôle (qui est l'IA), Objectif (ce que vous voulez), Contexte (détails et contraintes). Résultat parfait.",en:'A good prompt has 3 parts: Role (who the AI is), Goal (what you want), Context (details and constraints). That gives perfect results.'},
    analogy:{kw:"Tankou anboche yon ekspè: ou di l pòs li, travay la, ak kondisyon yo.",fr:"Comme embaucher un expert : vous lui donnez son poste, la tâche et les conditions.",en:"Like hiring an expert: you give them the role, the task, and the conditions."},
    example:{kw:"« Ou se yon ekspè maketing. Ekri 3 lejann Instagram pou yon restoran kreyòl nan Mayami. Ton cho, ak emoji. »",fr:"« Tu es un expert marketing. Écris 3 légendes Instagram pour un restaurant créole à Miami. Ton chaleureux, avec emojis. »",en:"“You are a marketing expert. Write 3 Instagram captions for a Creole restaurant in Miami. Warm tone, with emojis.”"},
    money:{kw:['Sèvis kreyasyon kontni pi rapid','Fòmasyon prompt'],fr:['Création de contenu plus rapide','Formation au prompt'],en:['Faster content-creation service','Prompt training']},
    quiz:{kw:{q:'Ki 3 pati yon bon prompt?',a:['Wòl, Objektif, Kontèks','Wo, Mi, Ba','Wouj, Vèt, Ble','Maten, Midi, Swa'],c:0},
          fr:{q:'Quelles sont les 3 parties d\'un bon prompt ?',a:['Rôle, Objectif, Contexte','Haut, Milieu, Bas','Rouge, Vert, Bleu','Matin, Midi, Soir'],c:0},
          en:{q:'What are the 3 parts of a good prompt?',a:['Role, Goal, Context','Top, Middle, Bottom','Red, Green, Blue','Morning, Noon, Night'],c:0}} },
  { id:3, sec:'Baz Prompt', icon:'📑',
    title:{kw:'Bay egzanp (few-shot)',fr:'Donner des exemples (few-shot)',en:'Give examples (few-shot)'},
    lesson:{kw:'Lè ou bay AI a 1-2 egzanp fòma ou vle a, li imite yo. Sa rele « few-shot » epi li amelyore presizyon anpil.',fr:"Quand vous donnez 1-2 exemples du format voulu, l'IA les imite. On appelle ça le « few-shot » et ça améliore beaucoup la précision.",en:'When you give the AI 1-2 examples of the format you want, it imitates them. This is called “few-shot” and it boosts accuracy a lot.'},
    analogy:{kw:"Tankou montre yon nouvo travayè kèk egzanp anvan li kòmanse — li konprann pi vit.",fr:"Comme montrer quelques exemples à un nouvel employé avant qu'il commence — il comprend plus vite.",en:"Like showing a new worker a few examples before they start — they get it faster."},
    example:{kw:"Bay 2 egzanp tit pwodwi ou renmen, epi mande AI a jenere 10 lòt nan menm stil la.",fr:"Donnez 2 exemples de titres de produits que vous aimez, puis demandez à l'IA d'en générer 10 autres dans le même style.",en:"Give 2 examples of product titles you like, then ask the AI to generate 10 more in the same style."},
    money:{kw:['Kontni konsistan pou mak','Sèvis ki swiv yon style gid'],fr:['Contenu cohérent pour les marques','Service respectant une charte de style'],en:['Consistent content for brands','Service that follows a style guide']},
    quiz:{kw:{q:'Ki sa « few-shot » vle di?',a:['Bay kèk egzanp pou gide AI','Tire foto','Yon ti kantite lajan','Pale dousman'],c:0},
          fr:{q:'Que veut dire « few-shot » ?',a:['Donner quelques exemples pour guider l\'IA','Prendre des photos','Une petite somme','Parler doucement'],c:0},
          en:{q:'What does “few-shot” mean?',a:['Giving a few examples to guide the AI','Taking photos','A small amount of money','Speaking softly'],c:0}} },
  { id:4, sec:'Prompt Avanse ak Lajan', icon:'🔄',
    title:{kw:'Iterasyon ak rafinman',fr:'Itération et raffinement',en:'Iteration and refining'},
    lesson:{kw:'Premye repons lan se yon kòmansman. Mande chanjman: « fè l pi kout », « chanje ton an », « ajoute yon egzanp ». Rafine jiskaske li pafè.',fr:"La première réponse est un début. Demandez des changements : « plus court », « change le ton », « ajoute un exemple ». Affinez jusqu'à la perfection.",en:'The first answer is a start. Ask for changes: “make it shorter,” “change the tone,” “add an example.” Refine until it’s perfect.'},
    analogy:{kw:"Tankou eskilte: ou wete ti moso jiskaske fòm nan parèt.",fr:"Comme sculpter : on retire des morceaux jusqu'à ce que la forme apparaisse.",en:"Like sculpting: you chip away until the shape appears."},
    example:{kw:"Apre premye brouyon an, Marie di: « Pi kout, ton pi pwofesyonèl, ajoute yon apèl aksyon » — twazyèm vèsyon an pafè.",fr:"Après le premier brouillon, Marie dit : « Plus court, ton plus pro, ajoute un appel à l'action » — la 3e version est parfaite.",en:"After the first draft, Marie says: “Shorter, more professional tone, add a call to action” — the third version is perfect."},
    money:{kw:['Kalite final = kliyan satisfè','Mwens tan = plis travay'],fr:['Qualité finale = clients satisfaits','Moins de temps = plus de travail'],en:['Final quality = happy clients','Less time = more work done']},
    quiz:{kw:{q:'Sa ou dwe fè ak premye repons AI a?',a:['Aksepte l toujou','Rafine l ak enstriksyon','Efase tout','Rekòmanse depi zewo'],c:1},
          fr:{q:'Que faire de la première réponse de l\'IA ?',a:['Toujours l\'accepter','L\'affiner avec des consignes','Tout effacer','Recommencer de zéro'],c:1},
          en:{q:'What should you do with the AI’s first answer?',a:['Always accept it','Refine it with instructions','Delete everything','Start over from scratch'],c:1}} },
  { id:5, sec:'Prompt Avanse ak Lajan', icon:'🎨',
    title:{kw:'Prompt pou imaj ak vwa',fr:'Prompts pour image et voix',en:'Prompts for image and voice'},
    lesson:{kw:'Pou imaj (Midjourney, DALL·E), dekri sijè, style, limyè, ak koulè. Pou vwa (ElevenLabs), chwazi ton ak emosyon. Detay = bon rezilta.',fr:"Pour l'image (Midjourney, DALL·E), décrivez sujet, style, lumière, couleurs. Pour la voix (ElevenLabs), choisissez ton et émotion. Détails = bons résultats.",en:'For images (Midjourney, DALL·E), describe subject, style, lighting, and color. For voice (ElevenLabs), choose tone and emotion. Detail = good results.'},
    analogy:{kw:"Tankou dekri yon foto bay yon atis: plis ou detaye, pi pre rezilta a ak sa w wè nan tèt ou.",fr:"Comme décrire une photo à un artiste : plus vous détaillez, plus le résultat colle à votre idée.",en:"Like describing a photo to an artist: the more detail, the closer the result to what's in your head."},
    example:{kw:"« Yon machann fwi nan yon mache Ayisyen, limyè maten, style fotografi reyalis, koulè cho » → bèl imaj.",fr:"« Une marchande de fruits dans un marché haïtien, lumière du matin, style photoréaliste, couleurs chaudes » → belle image.",en:"“A fruit vendor in a Haitian market, morning light, photorealistic style, warm colors” → a beautiful image."},
    money:{kw:['Kreye vizyèl pou biznis','Logo, afich, miniati videyo'],fr:['Créer des visuels pour entreprises','Logos, affiches, miniatures vidéo'],en:['Create visuals for businesses','Logos, posters, video thumbnails']},
    quiz:{kw:{q:'Pou bon imaj AI, ou dwe...',a:['Dekri style, limyè, koulè','Ekri yon sèl mo','Itilize majiskil','Pa bay detay'],c:0},
          fr:{q:'Pour une bonne image IA, il faut...',a:['Décrire style, lumière, couleurs','Écrire un seul mot','Utiliser des majuscules','Ne pas donner de détails'],c:0},
          en:{q:'For a good AI image, you should...',a:['Describe style, lighting, color','Write a single word','Use all caps','Give no details'],c:0}} },
  { id:6, sec:'Prompt Avanse ak Lajan', icon:'💰',
    title:{kw:'Vann prompt (Prompt packs)',fr:'Vendre des prompts (Prompt packs)',en:'Sell prompts (Prompt packs)'},
    lesson:{kw:'Ou ka pakaje pi bon prompt ou yo nan yon « pack » epi vann li. Biznis ak kreyatè peye pou prompt ki ekonomize tan.',fr:"Regroupez vos meilleurs prompts dans un « pack » et vendez-le. Entreprises et créateurs paient pour des prompts qui font gagner du temps.",en:'Bundle your best prompts into a “pack” and sell it. Businesses and creators pay for prompts that save time.'},
    analogy:{kw:"Tankou vann yon liv resèt: moun peye pou rezilta ki teste deja.",fr:"Comme vendre un livre de recettes : on paie pour des résultats déjà testés.",en:"Like selling a recipe book: people pay for results that are already tested."},
    example:{kw:"Yon kreyatè vann yon « 50 Prompt pou Restoran » pack a $15 sou Gumroad — revni pasif.",fr:"Un créateur vend un pack « 50 prompts pour restaurants » à 15 $ sur Gumroad — revenu passif.",en:"A creator sells a “50 Prompts for Restaurants” pack for $15 on Gumroad — passive income."},
    money:{kw:['Prompt packs $10-30','Fòmasyon prompt engineering','Sèvis prompt sou mezi'],fr:['Prompt packs 10-30 $','Formation en prompt engineering','Prompts sur mesure'],en:['Prompt packs $10-30','Prompt-engineering training','Custom prompt service']},
    quiz:{kw:{q:'Ki jan ou fè lajan ak prompt?',a:['Vann prompt packs ak fòmasyon','Sere yo sèlman','Bay yo gratis tout tan','Pa posib'],c:0},
          fr:{q:'Comment gagner de l\'argent avec les prompts ?',a:['Vendre des packs et des formations','Les garder pour soi','Les donner gratuitement','Impossible'],c:0},
          en:{q:'How do you make money with prompts?',a:['Sell prompt packs & training','Just keep them','Give them away forever','Not possible'],c:0}} }
];
