// 30 Jou AI — daily "Devwa" (action task) for each lesson, from the
// KreyòlAIHub PREMIUM course deck. Trilingual: kw (default) · fr · en.
window.KAH_DEVWA = {
  1:{kw:["Ale sou ChatGPT.com — kreye yon kont gratis","Ekri: « Ede m fè yon CV pou [wòl ou vle] » epi voye l","Pataje rezilta w nan kòmantè a — #30JouAI"],
     fr:["Allez sur ChatGPT.com et créez un compte gratuit","Écrivez : « Aide-moi à faire un CV pour [le poste visé] » puis envoyez","Partagez votre résultat en commentaire — #30JouAI"],
     en:["Go to ChatGPT.com and create a free account","Type: “Help me write a CV for [the role you want]” and send","Share your result in the comments — #30JouAI"]},
  2:{kw:["Gade yon videyo sou TikTok oswa YouTube jodi a","Remake ki tip kontni algoritm rekòmande w plis","Ekri 3 ide kontni ou ta ka kreye pou piblik Ayisyen"],
     fr:["Regardez une vidéo sur TikTok ou YouTube aujourd'hui","Notez quel type de contenu l'algorithme vous recommande le plus","Écrivez 3 idées de contenu pour le public haïtien"],
     en:["Watch a video on TikTok or YouTube today","Notice what kind of content the algorithm recommends most","Write 3 content ideas you could make for a Haitian audience"]},
  3:{kw:["Idantifye yon biznis lokal ki ta ka benefisye ak AI","Ekri kijan AI ta ka ede biznis sa ekonomize tan ak lajan","Pataje ide w nan kòmantè a — kominote a la pou ou!"],
     fr:["Identifiez une entreprise locale qui pourrait bénéficier de l'IA","Écrivez comment l'IA pourrait lui faire gagner du temps et de l'argent","Partagez votre idée en commentaire — la communauté est là !"],
     en:["Identify a local business that could benefit from AI","Write how AI could help it save time and money","Share your idea in the comments — the community is here for you!"]},
  4:{kw:["Fè yon lis: 10 kliyan ou pi souvan wè oswa konnen","Pou chak kliyan: ki jou yo achte, ki pwodwi, ki pri","Felisitasyon — ou fèk kreye premye dataset ou!"],
     fr:["Faites une liste : 10 clients que vous voyez ou connaissez souvent","Pour chacun : quel jour ils achètent, quel produit, quel prix","Félicitations — vous venez de créer votre premier dataset !"],
     en:["Make a list: 10 customers you see or know most often","For each: which day they buy, which product, which price","Congrats — you just created your first dataset!"]},
  5:{kw:["Mande ChatGPT: « Ki biznis mwen ka lanse nan Pòtoprens ak mwens pase $100? »","Chwazi yon ide ki enterese w pami repons yo","Pataje repons AI a nan kòmantè a — #30JouAI"],
     fr:["Demandez à ChatGPT : « Quel business lancer à Port-au-Prince avec moins de 100 $ ? »","Choisissez une idée qui vous intéresse parmi les réponses","Partagez la réponse de l'IA en commentaire — #30JouAI"],
     en:["Ask ChatGPT: “What business can I start in Port-au-Prince for under $100?”","Pick an idea that interests you from the answers","Share the AI's answer in the comments — #30JouAI"]},
  6:{kw:["Ale sou Canva.com — kreye yon kont gratis kounye a","Itilize Canva AI pou kreye yon logo pou yon biznis imajinè","Pataje imaj la sou rezo sosyal ak #30JouAI — wè reyaksyon yo!"],
     fr:["Allez sur Canva.com et créez un compte gratuit","Utilisez Canva AI pour créer un logo pour une entreprise imaginaire","Partagez l'image sur les réseaux avec #30JouAI — observez les réactions !"],
     en:["Go to Canva.com and create a free account","Use Canva AI to create a logo for an imaginary business","Share it on social media with #30JouAI — watch the reactions!"]},
  7:{kw:["Kreye premye videyo kout ou sou TikTok oswa YouTube (60 segond)","Sijè: « Sa mwen aprann sou AI jodi a » — pou piblik Ayisyen","Optimize ak yon bon tit ak hashtag #30JouAI"],
     fr:["Créez votre première vidéo courte sur TikTok ou YouTube (60 s)","Sujet : « Ce que j'apprends sur l'IA aujourd'hui » — pour le public haïtien","Optimisez avec un bon titre et le hashtag #30JouAI"],
     en:["Make your first short video on TikTok or YouTube (60 sec)","Topic: “What I learned about AI today” — for a Haitian audience","Optimize with a good title and the hashtag #30JouAI"]},
  8:{kw:["Ale sou YouTube — rechèch: « Machine Learning pou debitan »","Gade yon videyo 10 minit sou sijè a","Ekri 3 aplikasyon Machine Learning ou wè nan lavi chak jou"],
     fr:["Allez sur YouTube — cherchez : « Machine Learning pour débutants »","Regardez une vidéo de 10 minutes sur le sujet","Écrivez 3 applications du Machine Learning que vous voyez au quotidien"],
     en:["Go to YouTube — search: “Machine Learning for beginners”","Watch a 10-minute video on the topic","Write 3 Machine Learning applications you see in everyday life"]},
  9:{kw:["Ekri yon post Facebook: « 5 bagay mwen aprann sou Deep Learning jodi a »","Pataje an Kreyòl pou piblik Ayisyen — edike kominote a","Tag @KreyòlAIHub epi note angajman ou jwenn"],
     fr:["Écrivez un post Facebook : « 5 choses apprises sur le Deep Learning aujourd'hui »","Partagez en créole pour le public haïtien — éduquez la communauté","Taguez @KreyòlAIHub et notez l'engagement obtenu"],
     en:["Write a Facebook post: “5 things I learned about Deep Learning today”","Share it in Kreyòl for a Haitian audience — educate the community","Tag @KreyòlAIHub and note the engagement you get"]},
  10:{kw:["Kreye 3 logo diferan pou 3 biznis imajinè ak Canva AI","Poste yo sou Instagram oswa Facebook","Di piblik ou: « Ki logo ou pi renmen? Mwen fè sa an 3 minit ak AI. »"],
     fr:["Créez 3 logos différents pour 3 entreprises imaginaires avec Canva AI","Publiez-les sur Instagram ou Facebook","Demandez : « Quel logo préférez-vous ? Fait en 3 min avec l'IA. »"],
     en:["Create 3 different logos for 3 imaginary businesses with Canva AI","Post them on Instagram or Facebook","Ask your audience: “Which logo do you prefer? Made in 3 min with AI.”"]},
  11:{kw:["Kreye yon dataset senp: 10 egzanp imèl bon vs 10 spam","Panse kijan AI ta ka aprann distenge yo — ekri rezònman w","Eksplike konsèp Supervised Learning bay yon zanmi an Kreyòl"],
     fr:["Créez un dataset simple : 10 bons e-mails vs 10 spams","Réfléchissez : comment l'IA apprendrait à les distinguer — écrivez-le","Expliquez le Supervised Learning à un ami, en créole"],
     en:["Create a simple dataset: 10 good emails vs 10 spam","Think how AI would learn to tell them apart — write your reasoning","Explain Supervised Learning to a friend, in Kreyòl"]},
  12:{kw:["Ale nan boutik ou oswa mande yon machann lokal pou ede w","Idantifye 3 gwoup kliyan diferan (pa pri, frekans, pwodwi)","Eksplike kijan AI ta ka optimize vant pou chak gwoup"],
     fr:["Allez dans votre boutique ou demandez à un commerçant local","Identifiez 3 groupes de clients (par prix, fréquence, produit)","Expliquez comment l'IA optimiserait les ventes pour chaque groupe"],
     en:["Go to your shop or ask a local vendor to help you","Identify 3 different customer groups (by price, frequency, product)","Explain how AI could optimize sales for each group"]},
  13:{kw:["Kreye 2 post diferan sou menm sijè pou Facebook","Wè kilès ki gen plis angajman apre 24 èdtan","Sa se « manyèl » Reinforcement Learning ou — aprann ak rezilta!"],
     fr:["Créez 2 posts différents sur le même sujet pour Facebook","Voyez lequel obtient le plus d'engagement après 24 h","C'est votre « manuel » de Reinforcement Learning — apprenez par les résultats !"],
     en:["Create 2 different posts on the same topic for Facebook","See which gets more engagement after 24 hours","That's your hands-on Reinforcement Learning — learn from results!"]},
  14:{kw:["Idantifye yon konpetans ou deja genyen (kizin, mizik, biznis, edikasyon)","Mande ChatGPT kijan ou ka transfere konpetans sa pou kreye yon sèvis dijital","Ekri plan ou an nan 5 pwen — pataje li"],
     fr:["Identifiez une compétence que vous avez déjà (cuisine, musique, business, éducation)","Demandez à ChatGPT comment transférer cette compétence en service numérique","Écrivez votre plan en 5 points — partagez-le"],
     en:["Identify a skill you already have (cooking, music, business, education)","Ask ChatGPT how to transfer that skill into a digital service","Write your plan in 5 points — share it"]},
  15:{kw:["Kreye yon PDF senp (3-5 paj) sou yon sijè ou konnen","Mande ChatGPT pou ede w ekri li pwofesyonèlman","Poste l sou WhatsApp Business pou vann li a $5 nan rezo w"],
     fr:["Créez un PDF simple (3-5 pages) sur un sujet que vous maîtrisez","Demandez à ChatGPT de vous aider à le rédiger professionnellement","Publiez-le sur WhatsApp Business pour le vendre à 5 $ dans votre réseau"],
     en:["Create a simple PDF (3-5 pages) on a topic you know","Ask ChatGPT to help you write it professionally","Post it on WhatsApp Business to sell for $5 in your network"]},
  16:{kw:["Ekri yon atik 500 mo sou yon sijè ou renmen ak ChatGPT","Poste l sou Medium.com oswa yon blog gratis","Rechèch kijan ou ka vann kontni sa sou Fiverr"],
     fr:["Écrivez un article de 500 mots sur un sujet que vous aimez avec ChatGPT","Publiez-le sur Medium.com ou un blog gratuit","Cherchez comment vendre ce contenu sur Fiverr"],
     en:["Write a 500-word article on a topic you love with ChatGPT","Post it on Medium.com or a free blog","Research how to sell this content on Fiverr"]},
  17:{kw:["Kreye yon afich pou yon evènman imajinè (konsè kompa, maryaj)","Itilize Canva AI pou fè afich pwofesyonèl la","Konpare rezilta a ak yon dizinè tradisyonèl — diferans lan klè!"],
     fr:["Créez une affiche pour un événement imaginaire (concert kompa, mariage)","Utilisez Canva AI pour réaliser une affiche professionnelle","Comparez le résultat à un designer traditionnel — la différence est claire !"],
     en:["Create a poster for an imaginary event (kompa concert, wedding)","Use Canva AI to make the professional poster","Compare it to a traditional designer — the difference is clear!"]},
  18:{kw:["Ale sou ElevenLabs.io — kreye yon kont gratis","Kreye yon vwa atifisyèl an Kreyòl (30 segond)","Panse: ki tip kontni ou ta ka monetize ak vwa sa?"],
     fr:["Allez sur ElevenLabs.io — créez un compte gratuit","Créez une voix artificielle en créole (30 secondes)","Réfléchissez : quel contenu pourriez-vous monétiser avec cette voix ?"],
     en:["Go to ElevenLabs.io — create a free account","Create an artificial voice in Kreyòl (30 seconds)","Think: what content could you monetize with that voice?"]},
  19:{kw:["Kreye yon YouTube Short 60 segond ak Pictory oswa InVideo","Sijè: « AI ka fè X pou ou » — X = yon bagay konkrè pou Ayisyen","Poste l kounye a ak hashtag #KreyòlAIHub"],
     fr:["Créez un YouTube Short de 60 s avec Pictory ou InVideo","Sujet : « L'IA peut faire X pour vous » — X = concret pour les Haïtiens","Publiez-le maintenant avec le hashtag #KreyòlAIHub"],
     en:["Create a 60-sec YouTube Short with Pictory or InVideo","Topic: “AI can do X for you” — X = something concrete for Haitians","Post it now with the hashtag #KreyòlAIHub"]},
  20:{kw:["Ale sou ManyChat.com oswa Tidio.com — kreye yon kont gratis","Bati yon chatbot senp pou yon boutik imajinè","Teste l ak 3 kestyon diferan — wè kijan li reponn"],
     fr:["Allez sur ManyChat.com ou Tidio.com — créez un compte gratuit","Construisez un chatbot simple pour une boutique imaginaire","Testez-le avec 3 questions différentes — observez ses réponses"],
     en:["Go to ManyChat.com or Tidio.com — create a free account","Build a simple chatbot for an imaginary shop","Test it with 3 different questions — see how it responds"]},
  21:{kw:["Kreye yon dataset senp pou yon biznis ou konnen","20 ranje: dat, pwodwi, kantite, pri, kliyan (imajinè men reyalis)","Mande ChatGPT pou analize done sa yo — wè sa li jwenn"],
     fr:["Créez un dataset simple pour une entreprise que vous connaissez","20 lignes : date, produit, quantité, prix, client (imaginaire mais réaliste)","Demandez à ChatGPT d'analyser ces données — voyez ce qu'il trouve"],
     en:["Create a simple dataset for a business you know","20 rows: date, product, quantity, price, customer (imaginary but realistic)","Ask ChatGPT to analyze the data — see what it finds"]},
  22:{kw:["Kreye 5 prompt pwofesyonèl pou yon niche (restoran, lekòl, boutik)","Teste chak prompt ak ChatGPT — evalye rezilta yo","Chwazi pi bon 3 yo pou kreye yon Prompt Pack pou vann"],
     fr:["Créez 5 prompts professionnels pour une niche (restaurant, école, boutique)","Testez chaque prompt avec ChatGPT — évaluez les résultats","Choisissez les 3 meilleurs pour créer un Prompt Pack à vendre"],
     en:["Create 5 professional prompts for a niche (restaurant, school, shop)","Test each prompt with ChatGPT — evaluate the results","Pick the best 3 to build a Prompt Pack to sell"]},
  23:{kw:["Pratike fòmil la: Wòl + Objektif + Kontèks = Rezilta pafè","Ekri 3 prompt pou 3 domèn: edikasyon, biznis, kreyativite","Pataje pi bon rezilta w nan kòmantè a"],
     fr:["Pratiquez la formule : Rôle + Objectif + Contexte = Résultat parfait","Écrivez 3 prompts pour 3 domaines : éducation, business, créativité","Partagez votre meilleur résultat en commentaire"],
     en:["Practice the formula: Role + Goal + Context = perfect result","Write 3 prompts for 3 areas: education, business, creativity","Share your best result in the comments"]},
  24:{kw:["Mande ChatGPT pou rezime yon dokiman oswa atik long (5+ paj)","Mande l pou tradui yon tèks Kreyòl an Angle ak Fransè","Konpare kalite tradiksyon an ak yon tradiksyon manyèl — diferans?"],
     fr:["Demandez à ChatGPT de résumer un document ou un article long (5+ pages)","Demandez-lui de traduire un texte créole en anglais et en français","Comparez la qualité de la traduction à une traduction manuelle — la différence ?"],
     en:["Ask ChatGPT to summarize a long document or article (5+ pages)","Ask it to translate a Kreyòl text into English and French","Compare the translation quality to a manual one — the difference?"]},
  25:{kw:["Deside jodi a: Freelance, Ajans, oswa Pwodwi Dijital?","Ekri yon plan 30 jou pou premye sèvis oswa pwodwi ou","Pataje desizyon w nan kòmantè a — kominote a sipòte w!"],
     fr:["Décidez aujourd'hui : Freelance, Agence ou Produit numérique ?","Écrivez un plan de 30 jours pour votre premier service ou produit","Partagez votre décision en commentaire — la communauté vous soutient !"],
     en:["Decide today: Freelance, Agency, or Digital Product?","Write a 30-day plan for your first service or product","Share your decision in the comments — the community supports you!"]},
  26:{kw:["Idantifye 3 travay nan yon konpayi ou ta vle travay","Rechèch kijan AI itilize nan domèn sa yo","Ekri kijan konesans AI w ka ede konpayi a — sa se CV ou!"],
     fr:["Identifiez 3 postes dans une entreprise où vous aimeriez travailler","Cherchez comment l'IA est utilisée dans ces domaines","Écrivez comment votre savoir en IA peut aider l'entreprise — c'est votre CV !"],
     en:["Identify 3 jobs at a company you'd like to work for","Research how AI is used in those fields","Write how your AI knowledge can help the company — that's your CV!"]},
  27:{kw:["Chwazi yon sijè ou vle aprann (maketing, kodaj, Angle, finans)","Mande ChatGPT: « Kreye yon plan aprantisaj 30 jou pou mwen »","Kòmanse premye leson an jodi a — 15 minit sèlman!"],
     fr:["Choisissez un sujet à apprendre (marketing, code, anglais, finance)","Demandez à ChatGPT : « Crée-moi un plan d'apprentissage de 30 jours »","Commencez la première leçon aujourd'hui — 15 minutes seulement !"],
     en:["Choose a subject to learn (marketing, coding, English, finance)","Ask ChatGPT: “Create a 30-day learning plan for me”","Start the first lesson today — just 15 minutes!"]},
  28:{kw:["Kreye yon pwodwi « AI + Mwen »: powèm, chanson, oswa istwa kout an Kreyòl","Mande ChatGPT pou ede w amelyore li","Poste l sou rezo sosyal — piblik ou ap renmen li!"],
     fr:["Créez un produit « IA + Moi » : poème, chanson ou histoire courte en créole","Demandez à ChatGPT de vous aider à l'améliorer","Publiez-le sur les réseaux — votre public va l'adorer !"],
     en:["Create an “AI + Me” product: a poem, song, or short story in Kreyòl","Ask ChatGPT to help you improve it","Post it on social media — your audience will love it!"]},
  29:{kw:["Poze ChatGPT yon kesyon sou yon sijè ou konnen trè byen","Idantifye 2-3 erè oswa enfòmasyon ki manke nan repons li","Sa montre poukisa jijman imen rete enpòtan toujou!"],
     fr:["Posez à ChatGPT une question sur un sujet que vous maîtrisez très bien","Identifiez 2-3 erreurs ou informations manquantes dans sa réponse","Cela montre pourquoi le jugement humain reste essentiel !"],
     en:["Ask ChatGPT a question on a topic you know very well","Identify 2-3 errors or missing info in its answer","This shows why human judgment still matters!"]},
  30:{kw:["Ekri plan 6 mwa ou: Mwa 1-2 kontni, Mwa 3-4 sèvis, Mwa 5-6 pwodwi dijital","Chwazi niche ou epi pibliye premye ofisyèl ou jodi a","Pataje pakou w ak #30JouAI epi rejwenn kominote KreyòlAIHub la"],
     fr:["Écrivez votre plan 6 mois : Mois 1-2 contenu, 3-4 services, 5-6 produit numérique","Choisissez votre niche et publiez votre première offre aujourd'hui","Partagez votre parcours avec #30JouAI et rejoignez la communauté KreyòlAIHub"],
     en:["Write your 6-month plan: Months 1-2 content, 3-4 services, 5-6 digital product","Choose your niche and publish your first offer today","Share your journey with #30JouAI and join the KreyòlAIHub community"]}
};
