// 30 lessons for the KreyòlAIHub Academy. Trilingual content keyed by KW/FR/EN.
window.KAH_LESSONS = [
  // Week 1 — Fondasyon AI
  { id:1,  week:1, sec:'Fondasyon AI', icon:'🧠',
    title: { kw:'Ki sa ki AI?', fr:'Qu\'est-ce que l\'IA?', en:'What is AI?' },
    lesson:{ kw:'AI se kapasite òdinatè pou aprann, analize, epi pran desizyon. Li deja nan YouTube, Google Maps, Facebook ak telefòn ou.',
             fr:'L\'IA est la capacité d\'un ordinateur à apprendre, analyser et décider. Elle est déjà dans YouTube, Google Maps, Facebook.',
             en:'AI is a computer\'s ability to learn, analyze, and decide. It already lives inside YouTube, Google Maps, Facebook, your phone.' },
    analogy:{ kw:'Panse ak yon asistan dijital — li pa dòmi, li pa fatige, li pa mande salè. Li travay 24 sou 24.',
              fr:'Pensez à un assistant numérique — il ne dort jamais, ne fatigue jamais, ne demande pas de salaire.',
              en:'Think of a digital assistant — never sleeps, never tires, never asks for a salary. Works 24/7.' },
    example:{ kw:'Jean nan Pòtoprens te chome 6 mwa. ChatGPT ede l ekri CV. 2 semèn apre: travay $800/mwa.',
              fr:'Jean à Port-au-Prince, 6 mois au chômage. ChatGPT a écrit son CV. 2 semaines plus tard : 800$/mois.',
              en:'Jean in Port-au-Prince, jobless for 6 months. ChatGPT helped him write his CV. 2 weeks later: $800/month job.' },
    money: { kw:['Sèvis CV: $20–$50','Affiliate AI tools','Kontni edikatif Kreyòl'],
             fr:['Service CV : 20–50$','Affiliation outils IA','Contenu éducatif créole'],
             en:['CV writing service: $20–$50','AI tool affiliate','Creole education content'] },
    quiz:  { kw:{q:'Ki sa AI ye?',a:['Yon moun','Yon kapasite òdinatè','Yon telefòn','Yon aplikasyon sèlman'],c:1},
             fr:{q:'Qu\'est-ce que l\'IA ?',a:['Une personne','Une capacité d\'ordinateur','Un téléphone','Une seule app'],c:1},
             en:{q:'What is AI?',a:['A person','A computer capability','A phone','Just one app'],c:1} } },
  { id:2, week:1, sec:'Fondasyon AI', icon:'📚',
    title:{kw:'Kijan AI aprann?',fr:'Comment l\'IA apprend?',en:'How does AI learn?'},
    lesson:{kw:'AI aprann nan done. Chak fwa ou like, ou gade, ou klike — sistèm anrejistre sa. Plis done = plis presizyon.',
            fr:'L\'IA apprend des données. Chaque like, vue, clic est enregistré. Plus de données = plus de précision.',
            en:'AI learns from data. Every like, view, click is recorded. More data = more accuracy.'},
    analogy:{kw:'Machann nan mache Kafou: si kliyan achte plis diri chak vandredi, li mete plis diri vandredi. AI fè menm bagay ak milya done.',
             fr:'Comme une vendeuse au marché qui remarque ce que les clients achètent et ajuste son stock.',
             en:'Like a market vendor who notices what customers buy and adjusts their stock — but with billions of data points.'},
    example:{kw:'TikTok remake ou renmen videyo komik Ayisyen. Li montre w plis. Si ou kreye nan niche sa, algoritm an pouse w.',
             fr:'TikTok remarque que vous aimez les vidéos comiques haïtiennes et vous en montre plus.',
             en:'TikTok notices you love Haitian comedy videos and pushes more your way. Create in that niche, ride the algorithm.'},
    money:{kw:['Kontni optimize pou algoritm','YouTube monetization','TikTok affiliate'],
           fr:['Contenu optimisé','YouTube monétisation','Affiliation TikTok'],
           en:['Algo-optimized content','YouTube monetization','TikTok affiliate']},
    quiz:{kw:{q:'AI aprann nan ki bagay?',a:['Magi','Done','Lapriyè','Rèv'],c:1},
          fr:{q:'L\'IA apprend de quoi ?',a:['Magie','Données','Prières','Rêves'],c:1},
          en:{q:'AI learns from what?',a:['Magic','Data','Prayer','Dreams'],c:1}} },
  { id:3, week:1, sec:'Fondasyon AI', icon:'🌍',
    title:{kw:'Ki kote AI itilize?',fr:'Où l\'IA est-elle utilisée?',en:'Where is AI used?'},
    lesson:{kw:'AI nan Bank, Lopital, Rezo sosyal, E-commerce. AI pa lavni — li prezan jodi a.',
            fr:'L\'IA est partout : banques, hôpitaux, réseaux sociaux. Ce n\'est pas le futur, c\'est maintenant.',
            en:'AI is everywhere: banks, hospitals, social media, e-commerce. Not the future — it is now.'},
    analogy:{kw:'Tankou elektrisite: premye moun ki konprann li te bati biznis. AI se nouvo elektrisite dijital la.',
             fr:'Comme l\'électricité : les premiers à comprendre ont bâti des empires.',
             en:'Like electricity: the first to understand built empires. AI is the new digital electricity.'},
    example:{kw:'Restoran Pétion-Ville itilize chatbot pou pran kòmand 24/7. Ekonomize 4 èdtan/jou.',
             fr:'Un restaurant à Pétion-Ville utilise un chatbot pour les commandes 24/7. 4h économisées/jour.',
             en:'A Pétion-Ville restaurant uses a chatbot for orders 24/7. Saves 4 hours a day.'},
    money:{kw:['Chatbot pou restoran','Repons otomatik pou klinik','Konsiltasyon dijital'],
           fr:['Chatbots restaurants','Réponses cliniques','Conseil numérique'],
           en:['Chatbots for restaurants','Auto-replies for clinics','Digital consulting']},
    quiz:{kw:{q:'AI itilize nan ki domèn?',a:['Sèlman jwèt','Sèlman bank','Anpil domèn','Pa anyen'],c:2},
          fr:{q:'L\'IA est utilisée dans...',a:['Que les jeux','Que les banques','Beaucoup','Nulle part'],c:2},
          en:{q:'AI is used in...',a:['Only games','Only banks','Many fields','Nowhere'],c:2}} },
  { id:4, week:1, sec:'Fondasyon AI', icon:'📊',
    title:{kw:'Ki sa ki done?',fr:'Qu\'est-ce que la donnée?',en:'What is data?'},
    lesson:{kw:'Done = enfòmasyon. Lis kliyan, email, istorik acha, preferans. AI manje done. Bon done = bon rezilta.',
            fr:'Données = information. Listes clients, emails, achats, préférences. L\'IA mange des données.',
            en:'Data = information. Customer lists, emails, purchase history, preferences. AI eats data. Good data = good results.'},
    analogy:{kw:'Tankou manje pou yon moun: si ou bay move manje, sante pa bon. Done se manje AI.',
             fr:'Comme la nourriture pour une personne. Mauvaise nourriture, mauvaise santé.',
             en:'Like food for a person — bad food, bad health. Data is AI\'s food.'},
    example:{kw:'Boutik nan katye ou: konnen ki pwodwi vann plis, ki jou plis kliyan, ki pri ki mache.',
             fr:'Une boutique de quartier qui sait quels produits, jours et prix marchent.',
             en:'A neighborhood shop knowing which products sell most, busiest days, best price points.'},
    money:{kw:['Analiz mache lokal','Kolekte done kliyan','Stratèji kontni'],
           fr:['Analyse marché local','Collecte clients','Stratégie contenu'],
           en:['Local market analysis','Customer data collection','Content strategy']},
    quiz:{kw:{q:'Sa AI bezwen pou aprann?',a:['Lajan','Done','Tan','Krèm'],c:1},
          fr:{q:'L\'IA a besoin de...',a:['Argent','Données','Temps','Crème'],c:1},
          en:{q:'AI needs...',a:['Money','Data','Time','Cream'],c:1}} },
  { id:5, week:1, sec:'Fondasyon AI', icon:'⚖️',
    title:{kw:'Kijan AI pran desizyon?',fr:'Comment l\'IA décide?',en:'How does AI decide?'},
    lesson:{kw:'AI pran desizyon sou baz pwobabilite. Li pa panse — li kalkile. Li chwazi opsyon ki gen plis chans mache.',
            fr:'L\'IA décide par probabilités. Elle ne pense pas, elle calcule — choisit l\'option la plus probable.',
            en:'AI decides by probability. It doesn\'t think — it calculates. Picks the option with the highest odds.'},
    analogy:{kw:'Machann ki konnen: si lapli tonbe, lavant diminye. Se eksperyans + estatistik.',
             fr:'Une vendeuse expérimentée qui sait que la pluie réduit les ventes.',
             en:'An experienced vendor who knows rain cuts sales. Experience + statistics — that\'s AI with billions of data points.'},
    example:{kw:'Mande AI: ki biznis nan kapital la? ki pri kliyan pare pou peye? Sa ki te koute $1,000 vin gratis.',
             fr:'Demandez à l\'IA : quel business lancer ? Le conseil qui coûtait 1000$ est gratuit.',
             en:'Ask AI: what business should I start? What price will customers pay? Consulting that cost $1,000 is now free.'},
    money:{kw:['Plan biznis pou kliyan','Analiz konpetisyon','Stratèji piblisite'],
           fr:['Plans business clients','Analyse concurrence','Stratégie pub'],
           en:['Business plans for clients','Competitor analysis','Ad strategy']},
    quiz:{kw:{q:'AI pran desizyon ak...',a:['Emosyon','Pwobabilite','Asar','Konsèl zanmi'],c:1},
          fr:{q:'L\'IA décide par...',a:['Émotion','Probabilité','Hasard','Conseils'],c:1},
          en:{q:'AI decides by...',a:['Emotion','Probability','Randomness','Friend advice'],c:1}} },

  // Week 1 cont — section 2: Zouti & Premye Lajan
  { id:6, week:1, sec:'Zouti & Premye Lajan', icon:'🛠️',
    title:{kw:'Modèl AI yo',fr:'Les modèles d\'IA',en:'AI Models'},
    lesson:{kw:'Modèl AI = sèvo espesyalize. ChatGPT pou tèks, Canva AI pou dizèn, Midjourney pou imaj, ElevenLabs pou vwa.',
            fr:'Modèle IA = cerveau spécialisé. ChatGPT (texte), Canva AI (design), Midjourney (image), ElevenLabs (voix).',
            en:'An AI model is a specialized brain. ChatGPT for text, Canva AI for design, Midjourney for image, ElevenLabs for voice.'},
    analogy:{kw:'Tankou yon rara: youn jwe tanbou, youn vaksen, youn kòn. Chak modèl gen rol li.',
             fr:'Comme un rara : chaque instrument a son rôle.',
             en:'Like a rara band — each instrument has a role. Each AI model too.'},
    example:{kw:'Michèle te peye $200 pa logo. Apre Canva AI, li kreye pou lòt biznis. Premye mwa: 12 logo = $600.',
             fr:'Michèle payait 200$/logo. Avec Canva AI, elle en crée pour d\'autres : 600$ le 1er mois.',
             en:'Michèle used to pay $200 per logo. With Canva AI she now sells to others: $600 in month one.'},
    money:{kw:['Logo $40–$80','Afich pou evènman','Menu restoran','Fiverr/Marketplace'],
           fr:['Logo 40–80$','Affiches','Menus restaurant','Fiverr'],
           en:['Logos $40–$80','Event posters','Restaurant menus','Fiverr / Marketplace']},
    quiz:{kw:{q:'ChatGPT se yon...',a:['Telefòn','Modèl AI tèks','Aplikasyon foto','Jwèt'],c:1},
          fr:{q:'ChatGPT est un...',a:['Téléphone','Modèle texte','App photo','Jeu'],c:1},
          en:{q:'ChatGPT is a...',a:['Phone','Text AI model','Photo app','Game'],c:1}} },
  { id:7, week:1, sec:'Zouti & Premye Lajan', icon:'📈',
    title:{kw:'Algoritm yo',fr:'Les algorithmes',en:'Algorithms'},
    lesson:{kw:'Algoritm deside ki videyo monte sou TikTok, Facebook, YouTube. Li mezire tan gade, kòmantè, pataj.',
            fr:'L\'algorithme décide ce qui monte sur TikTok, FB, YouTube. Il mesure temps, commentaires, partages.',
            en:'Algorithms decide what gets pushed on TikTok, FB, YouTube — measuring watch time, comments, shares.'},
    analogy:{kw:'Tankou radyo ki mete mizik moun rele mande plis: si moun mande konpa, radyo mete konpa.',
             fr:'Comme une radio qui passe ce que les gens redemandent.',
             en:'Like a radio that plays what listeners keep requesting.'},
    example:{kw:'Marie nan Delma kòmanse poste videyo AI an Kreyòl. Apre 30 jou: 50,000 views, premye komisyon.',
             fr:'Marie poste des vidéos IA en créole : 50 000 vues en 30 jours, première commission.',
             en:'Marie posts AI-in-Creole videos. 30 days in: 50,000 views, first affiliate commission.'},
    money:{kw:['YouTube monetization','TikTok Creator Fund','Affiliate marketing'],
           fr:['YouTube monétisé','TikTok Creator Fund','Affiliation'],
           en:['YouTube monetization','TikTok Creator Fund','Affiliate marketing']},
    quiz:{kw:{q:'Algoritm gen emosyon?',a:['Wi','Non, li swiv done','Pafwa','Lè ou mande l'],c:1},
          fr:{q:'L\'algo a des émotions ?',a:['Oui','Non, il suit les données','Parfois','Sur demande'],c:1},
          en:{q:'Algos have emotions?',a:['Yes','No, they follow data','Sometimes','On request'],c:1}} },
  { id:8, week:1, sec:'Zouti & Premye Lajan', icon:'🤖',
    title:{kw:'Machine Learning',fr:'Machine Learning',en:'Machine Learning'},
    lesson:{kw:'Machine Learning = fason AI vin pi bon apre chak erè. Li teste, korije, amelyore.',
            fr:'Le Machine Learning, c\'est comment l\'IA s\'améliore après chaque erreur.',
            en:'Machine Learning is how AI gets better after each mistake — test, correct, improve.'},
    analogy:{kw:'Tankou chofè tap-tap k ap aprann wout: premye semèn move chemen, apre 3 mwa li metrize trafik.',
             fr:'Comme un chauffeur de tap-tap qui apprend la route en quelques mois.',
             en:'Like a tap-tap driver learning routes — bad week one, master in three months.'},
    example:{kw:'Spotify remake ou renmen Harmonik plis pase Tabou Combo. Li rekòmande plis menm stil.',
             fr:'Spotify remarque vos goûts et recommande davantage du même style.',
             en:'Spotify notices you prefer one band over another and pushes more of that style.'},
    money:{kw:['Mini-kou sou ML','Fòmasyon AI Kreyòl','Konsiltasyon biznis'],
           fr:['Mini-cours ML','Formation IA créole','Conseil entreprises'],
           en:['Mini-courses on ML','Creole AI training','Business consulting']},
    quiz:{kw:{q:'ML vle di:',a:['Mache lokal','Aprantisaj machin','Mizik latifèl','Modèl lib'],c:1},
          fr:{q:'ML signifie :',a:['Marché local','Apprentissage machine','Musique latine','Modèle libre'],c:1},
          en:{q:'ML stands for:',a:['Mobile Learn','Machine Learning','Music Library','Model Lab'],c:1}} },
  { id:9, week:1, sec:'Zouti & Premye Lajan', icon:'🧬',
    title:{kw:'Deep Learning',fr:'Deep Learning',en:'Deep Learning'},
    lesson:{kw:'Deep Learning pèmèt rekonèt vizaj, tradui lang, kreye videyo ak vwa. Se teknoloji dèyè ChatGPT ak Midjourney.',
            fr:'Deep Learning : reconnaissance, traduction, vidéo, voix. Le moteur derrière ChatGPT et Midjourney.',
            en:'Deep Learning enables face recognition, translation, video, voice. The tech behind ChatGPT and Midjourney.'},
    analogy:{kw:'Panse ak sèvo moun: gen anpil kouch panse. Deep Learning gen anpil kouch kalkil.',
             fr:'Comme un cerveau avec plusieurs couches de pensée.',
             en:'Like a brain with many layers of thought. More layers, more capability.'},
    example:{kw:'Kamera sekirite ka rekonèt figi gras a Deep Learning. Teknoloji a la, nan men moun ki konnen.',
             fr:'Les caméras reconnaissent les visages grâce au Deep Learning.',
             en:'Security cameras recognize faces thanks to Deep Learning. The tech is here for those who know.'},
    money:{kw:['Kontni edikatif AI','Pozisyone tèt ou ekspè','Konsiltasyon teknoloji'],
           fr:['Contenu IA','Se positionner expert','Conseil tech'],
           en:['AI education content','Position yourself expert','Tech consulting']},
    quiz:{kw:{q:'Deep Learning gen...',a:['Yon sèl kouch','Anpil kouch','Pa gen kouch','Kouch koulè'],c:1},
          fr:{q:'Deep Learning a...',a:['Une couche','Plusieurs couches','Aucune','Couches colorées'],c:1},
          en:{q:'Deep Learning has...',a:['One layer','Many layers','No layers','Color layers'],c:1}} },
  { id:10, week:1, sec:'Zouti & Premye Lajan', icon:'🎨',
    title:{kw:'Kreye logo ak AI',fr:'Créer un logo avec l\'IA',en:'Create a logo with AI'},
    lesson:{kw:'Ak AI ou ka kreye logo, menu, bann, branding konplè. Sa ki te mande dizinè chè vin posib an 3 minit.',
            fr:'Avec l\'IA : logos, menus, bannières, branding complet — en 3 minutes.',
            en:'With AI: logos, menus, banners, full branding — in 3 minutes.'},
    analogy:{kw:'Tankou aprann fè griyo lakay olye peye restoran chak fwa.',
             fr:'Comme apprendre à cuisiner chez soi plutôt que payer le resto.',
             en:'Like learning to cook at home instead of paying restaurants every time.'},
    example:{kw:'Yon jèn nan Carrefour kreye logo pou 5 ti biznis nan katye li. $40/logo = $200 nan yon semèn.',
             fr:'Un jeune à Carrefour fait 5 logos à 40$ : 200$ en une semaine.',
             en:'A young creator in Carrefour did 5 logos at $40 each — $200 in one week.'},
    money:{kw:['Fiverr / Marketplace','WhatsApp Business','2 logo/jou = $2,000/mwa'],
           fr:['Fiverr','WhatsApp Business','2 logos/jour = 2000$/mois'],
           en:['Fiverr / Marketplace','WhatsApp Business','2 logos/day = ~$2,000/month']},
    quiz:{kw:{q:'Pou kreye logo ak AI ou bezwen:',a:['$1000','Yon zouti tankou Canva AI','Ekspè 10 ane','Anyen'],c:1},
          fr:{q:'Pour un logo IA, il faut :',a:['1000$','Un outil comme Canva AI','10 ans d\'expérience','Rien'],c:1},
          en:{q:'For an AI logo you need:',a:['$1000','A tool like Canva AI','10 yrs experience','Nothing'],c:1}} },

  // Week 2 — Lajan ak AI / Revni Pasif
  { id:11, week:2, sec:'Lajan ak AI', icon:'🎯',
    title:{kw:'Supervised Learning',fr:'Apprentissage supervisé',en:'Supervised Learning'},
    lesson:{kw:'AI aprann ak egzanp klè. Ou montre li sa ki kòrèk ak sa ki pa kòrèk. Li ajiste modèl li.',
            fr:'L\'IA apprend par exemples étiquetés : ce qui est juste, ce qui ne l\'est pas.',
            en:'AI learns from labeled examples — what\'s right, what\'s wrong, then adjusts.'},
    analogy:{kw:'Pwofesè k ap montre timoun ekri lèt A. Premye fwa erè. Apre 20 fwa: metrize.',
             fr:'Un prof qui apprend la lettre A à un enfant — erreur, puis maîtrise.',
             en:'A teacher showing a kid how to write "A" — mistakes first, mastery after 20 tries.'},
    example:{kw:'Bank bay modèl la 1,000 egzanp chèk reyèl ak fo. Sistèm aprann blòk fo chèk otomatikman.',
             fr:'Une banque entraîne un modèle sur 1000 chèques vrais/faux. Détection auto.',
             en:'A bank trains a model on 1,000 real vs fake check examples — auto-detects forgeries.'},
    money:{kw:['Anseye AI nan kou','Kreye fòmasyon lekòl','Vann workshop AI'],
           fr:['Enseigner l\'IA','Formations écoles','Ateliers IA'],
           en:['Teach AI in courses','School training','Sell AI workshops']},
    quiz:{kw:{q:'Supervised Learning bezwen:',a:['Pa anyen','Egzanp ki etikèt','Lajan','Travay manyèl'],c:1},
          fr:{q:'L\'apprentissage supervisé requiert :',a:['Rien','Des exemples étiquetés','De l\'argent','Du travail manuel'],c:1},
          en:{q:'Supervised Learning needs:',a:['Nothing','Labeled examples','Money','Manual work'],c:1}} },
  { id:12, week:2, sec:'Lajan ak AI', icon:'🔍',
    title:{kw:'Unsupervised Learning',fr:'Apprentissage non supervisé',en:'Unsupervised Learning'},
    lesson:{kw:'AI pa resevwa repons pare. Li analize done epi dekouvri modèl poukont li.',
            fr:'Sans réponses fournies, l\'IA découvre des motifs cachés.',
            en:'No answers given — AI analyzes data and discovers patterns on its own.'},
    analogy:{kw:'Komèsan ki remake: moun ki achte diri souvan achte lwil tou. Pa gen moun ki di l sa.',
             fr:'Un commerçant qui remarque seul : les acheteurs de riz achètent aussi de l\'huile.',
             en:'A shopkeeper who notices on her own that rice buyers also buy oil.'},
    example:{kw:'Boutik telefòn dekouvri kliyan ki achte telefòn achte kask 3 jou apre.',
             fr:'Boutique téléphone : clients qui achètent un téléphone achètent un casque 3 jours après.',
             en:'A phone shop notices customers buy headphones 3 days after a phone purchase.'},
    money:{kw:['Analiz kliyan','Stratèji pwomosyon','Konsiltasyon mache'],
           fr:['Analyse clients','Stratégies promo','Conseil marché'],
           en:['Customer analysis','Smart promotions','Market consulting']},
    quiz:{kw:{q:'Unsupervised Learning:',a:['Bezwen pwofesè','Dekouvri pa kont li','Bezwen Wi-Fi','Bezwen lajan'],c:1},
          fr:{q:'Non supervisé veut dire :',a:['Besoin de prof','Découvre seul','Besoin Wi-Fi','Besoin argent'],c:1},
          en:{q:'Unsupervised means:',a:['Needs teacher','Discovers alone','Needs Wi-Fi','Needs money'],c:1}} },
  { id:13, week:2, sec:'Lajan ak AI', icon:'🔁',
    title:{kw:'Reinforcement Learning',fr:'Apprentissage par renforcement',en:'Reinforcement Learning'},
    lesson:{kw:'AI aprann nan erè. Li teste, wè rezilta, ajiste. Chak erè vin amelyorasyon.',
            fr:'L\'IA apprend de ses erreurs : tester, observer, ajuster.',
            en:'AI learns by mistakes — test, observe outcome, adjust. Each error is improvement.'},
    analogy:{kw:'Tankou timoun k ap aprann monte bisiklèt. Tonbe 10 fwa, apre sa li metrize.',
             fr:'Comme apprendre à faire du vélo : on tombe 10 fois puis on maîtrise.',
             en:'Like a kid learning to ride a bike — falls 10 times, then mastery.'},
    example:{kw:'Kanpay Facebook Ads: AI teste 3 piblisite, remake kiyès ki bay plis lavant, optimize otomatikman.',
             fr:'Facebook Ads : l\'IA teste 3 pubs, garde celle qui convertit le mieux.',
             en:'Facebook Ads: AI tests 3 ad creatives, doubles down on the winner automatically.'},
    money:{kw:['Optimize ads kliyan','Jesyon ads FB/IG','Stratèji maketing'],
           fr:['Optimisation pub','Gestion FB/IG ads','Stratégie marketing'],
           en:['Client ad optimization','FB/IG ad management','Marketing strategy']},
    quiz:{kw:{q:'Reinforcement Learning ankouraje:',a:['Pa fè erè','Aprann nan erè','Pa eseye','Tann'],c:1},
          fr:{q:'Renforcement encourage :',a:['Pas d\'erreur','Apprendre par erreur','Ne pas essayer','Attendre'],c:1},
          en:{q:'Reinforcement Learning rewards:',a:['No mistakes','Learning from mistakes','Not trying','Waiting'],c:1}} },
  { id:14, week:2, sec:'Lajan ak AI', icon:'🔀',
    title:{kw:'Transfer Learning',fr:'Apprentissage par transfert',en:'Transfer Learning'},
    lesson:{kw:'AI itilize sa li deja konnen pou aprann nouvo bagay pi rapid. Ou pa kòmanse a zewo.',
            fr:'L\'IA réutilise ses connaissances pour apprendre plus vite.',
            en:'AI uses what it already knows to learn new things faster — no starting from zero.'},
    analogy:{kw:'Si ou deja konn Franse, aprann Espayòl vin pi fasil. Gen mo ki sanble.',
             fr:'Si tu sais le français, l\'espagnol vient plus vite.',
             en:'If you already know French, Spanish comes faster — shared roots.'},
    example:{kw:'Moun ki metrize ChatGPT aprann Claude oswa Gemini pi rapid — pa kòmanse nan zewo.',
             fr:'Maîtriser ChatGPT aide à apprendre Claude ou Gemini plus vite.',
             en:'Mastering ChatGPT speeds up learning Claude or Gemini — no starting from scratch.'},
    money:{kw:['Adapte sèvis ou rapid','Lanse pwodwi vit','Vitès = avantaj'],
           fr:['Adapter services rapidement','Lancer vite','Vitesse = avantage'],
           en:['Adapt services quickly','Launch products faster','Speed = advantage']},
    quiz:{kw:{q:'Transfer Learning vle di:',a:['Kòmanse depi zewo','Reyitilize konesans','Pèdi konesans','Padon'],c:1},
          fr:{q:'Transfer Learning veut dire :',a:['Recommencer','Réutiliser','Oublier','Pardon'],c:1},
          en:{q:'Transfer Learning means:',a:['Start over','Reuse knowledge','Forget','Pardon'],c:1}} },
  { id:15, week:2, sec:'Lajan ak AI', icon:'💰',
    title:{kw:'Revni Pasif ak AI',fr:'Revenus passifs avec l\'IA',en:'Passive Income with AI'},
    lesson:{kw:'Revni pasif = lajan ki antre menm lè ou pa travay dirèkteman. AI pèmèt sa paske li otomatik.',
            fr:'Revenu passif : argent qui rentre même quand tu ne travailles pas. L\'IA rend ça possible.',
            en:'Passive income — money flowing in while you sleep. AI makes it possible because it\'s automatic.'},
    analogy:{kw:'Travay aktif = limite. Sistèm otomatik = san limit.',
             fr:'Travail actif = limité. Système automatique = illimité.',
             en:'Active work = capped by hours. Automatic systems = uncapped.'},
    example:{kw:'Samuel nan dyaspora kreye PDF 10 paj "AI pou Biznis". Vann $17. 200 acha = $3,400 pasif.',
             fr:'Samuel crée un PDF "IA Business" à 17$. 200 ventes = 3400$ passifs.',
             en:'Samuel made a 10-page PDF "AI for Business" at $17. 200 sales = $3,400 passive.'},
    money:{kw:['Affiliate','Mini-kou $47','Sèvis otomatik','1 vant/jou = $940/mwa'],
           fr:['Affiliation','Mini-cours 47$','Services auto','1 vente/jour = 940$'],
           en:['Affiliate','Mini-courses $47','Automated services','1 sale/day = $940/mo']},
    quiz:{kw:{q:'Revni pasif:',a:['Travay tout tan','Lajan otomatik','Lwèt','Sa pa egziste'],c:1},
          fr:{q:'Revenu passif :',a:['Travailler sans cesse','Argent automatique','Loterie','N\'existe pas'],c:1},
          en:{q:'Passive income:',a:['Constant work','Automatic money','Lottery','Doesn\'t exist'],c:1}} },

  // Week 3 — Zouti Konkrè
  { id:16, week:3, sec:'Zouti Konkrè', icon:'✍️',
    title:{kw:'NLP — Ekri pou lajan',fr:'NLP — Écrire pour gagner',en:'NLP — Write for money'},
    lesson:{kw:'NLP = Natural Language Processing. AI ka ekri atik, CV, plan biznis, caption.',
            fr:'NLP : l\'IA écrit articles, CV, plans, légendes.',
            en:'NLP — AI writes articles, CVs, business plans, captions.'},
    analogy:{kw:'Tankou gen yon ekriven pwofesyonèl lakay ou 24 sou 24.',
             fr:'Comme avoir un écrivain à domicile 24/7.',
             en:'Like a professional writer in your house 24/7 — never tired, never complaining.'},
    example:{kw:'Jèn nan Gonaïves ekri atik blog touris Ayiti ak ChatGPT. Vann $50 chak sou Fiverr.',
             fr:'À Gonaïves, des articles tourisme rédigés via ChatGPT et vendus 50$ sur Fiverr.',
             en:'A creator in Gonaïves writes tourism-Haiti blogs via ChatGPT — $50 each on Fiverr.'},
    money:{kw:['Sèvis CV','Redaksyon atik','Copywriting','Deskripsyon pwodwi'],
           fr:['Service CV','Rédaction','Copywriting','Descriptions'],
           en:['CV writing','Article writing','Copywriting','Product descriptions']},
    quiz:{kw:{q:'NLP itilize pou:',a:['Imaj','Tèks','Vwa sèlman','Mizik'],c:1},
          fr:{q:'NLP sert pour :',a:['Images','Texte','Voix','Musique'],c:1},
          en:{q:'NLP is for:',a:['Images','Text','Voice only','Music'],c:1}} },
  { id:17, week:3, sec:'Zouti Konkrè', icon:'🖼️',
    title:{kw:'Computer Vision — Imaj AI',fr:'Computer Vision — Images IA',en:'Computer Vision — AI Images'},
    lesson:{kw:'Computer Vision pèmèt AI kreye oswa analize imaj. Zouti: Canva AI, Midjourney, Adobe Firefly.',
            fr:'Computer Vision : créer/analyser des images. Canva AI, Midjourney, Firefly.',
            en:'Computer Vision creates or reads images. Canva AI, Midjourney, Adobe Firefly.'},
    analogy:{kw:'Tankou gen yon estidyo dizèn dijital nan telefòn ou.',
             fr:'Comme un studio de design dans votre poche.',
             en:'A design studio in your pocket.'},
    example:{kw:'Restoran Pétion-Ville: jèn itilize Canva AI pou yon nouvo menu, chaje $80. Kliyan kontan.',
             fr:'Restaurant Pétion-Ville : nouveau menu en Canva AI, facturé 80$.',
             en:'Pétion-Ville restaurant gets a new menu in Canva AI — $80 invoiced. Client thrilled.'},
    money:{kw:['Fiverr','WhatsApp Business','Instagram portfolio'],
           fr:['Fiverr','WhatsApp Business','Portfolio Instagram'],
           en:['Fiverr','WhatsApp Business','Instagram portfolio']},
    quiz:{kw:{q:'Computer Vision se pou:',a:['Tèks','Imaj','Mizik','Lapòs'],c:1},
          fr:{q:'Computer Vision sert à :',a:['Texte','Images','Musique','Poste'],c:1},
          en:{q:'Computer Vision is for:',a:['Text','Images','Music','Mail'],c:1}} },
  { id:18, week:3, sec:'Zouti Konkrè', icon:'🎙️',
    title:{kw:'AI Audio — Vwa atifisyèl',fr:'IA Audio — Voix synthétiques',en:'AI Audio — Synthetic voices'},
    lesson:{kw:'AI ka kreye vwa natirèl. Pa bezwen mikwo chè oswa estidyo. Zouti: ElevenLabs, PlayHT, Suno.',
            fr:'L\'IA crée des voix naturelles : ElevenLabs, PlayHT, Suno (musique).',
            en:'AI creates natural voices — no expensive mic or studio. ElevenLabs, PlayHT, Suno.'},
    analogy:{kw:'Tankou gen yon prezantatè radyo dijital — disponib nenpòt ki lè.',
             fr:'Comme un présentateur radio dispo 24/7.',
             en:'Like a radio host available 24/7.'},
    example:{kw:'Yon podcast istwa Ayiti ak narasyon AI, monetize sou YouTube.',
             fr:'Un podcast d\'histoire haïtienne narré par IA, monétisé sur YouTube.',
             en:'A Haiti-history podcast narrated by AI, monetized on YouTube.'},
    money:{kw:['Podcast monetize','Voiceover videyo','Audio TikTok','Liv odyo Kreyòl'],
           fr:['Podcasts','Voix off','Audio TikTok','Livres audio créole'],
           en:['Podcast monetization','Voiceover work','TikTok audio','Creole audiobooks']},
    quiz:{kw:{q:'AI Audio kreye:',a:['Imaj','Vwa','Tèks','Estatistik'],c:1},
          fr:{q:'AI Audio crée :',a:['Images','Voix','Textes','Stats'],c:1},
          en:{q:'AI Audio creates:',a:['Images','Voices','Text','Stats'],c:1}} },
  { id:19, week:3, sec:'Zouti Konkrè', icon:'🎬',
    title:{kw:'AI Video — Viral + revni',fr:'IA Vidéo — Viral et revenus',en:'AI Video — Viral + revenue'},
    lesson:{kw:'AI kreye videyo rapid. Zouti: Runway, Pictory, InVideo. Kreye Shorts, explainer, videyo otomatik.',
            fr:'L\'IA produit des vidéos rapidement : Runway, Pictory, InVideo.',
            en:'AI produces video fast — Runway, Pictory, InVideo. Shorts, explainers, auto-videos.'},
    analogy:{kw:'Tankou gen yon ekip pwodiksyon mini Hollywood nan laptop ou.',
             fr:'Comme une équipe de prod Hollywood dans votre laptop.',
             en:'Like a mini-Hollywood crew inside your laptop.'},
    example:{kw:'Kanal "AI pou Ayiti" poste 3 Shorts/jou. Apre 90 jou: monetize.',
             fr:'Une chaîne "IA pour Haïti" : 3 Shorts/jour, monétisée en 90 jours.',
             en:'A channel "AI for Haiti" posts 3 Shorts a day. 90 days in: monetized.'},
    money:{kw:['Ad revenue','Affiliate','Sponsorship','Sèvis video edit'],
           fr:['Revenus pubs','Affiliation','Sponsors','Montage vidéo'],
           en:['Ad revenue','Affiliate','Sponsorships','Video edit services']},
    quiz:{kw:{q:'AI Video pèmèt:',a:['Kreye videyo rapid','Sèlman li','Anyen','Pal sèlman'],c:0},
          fr:{q:'AI Video permet :',a:['Créer vite','Lire seulement','Rien','Parler'],c:0},
          en:{q:'AI Video lets you:',a:['Create video fast','Just read','Nothing','Only speak'],c:0}} },
  { id:20, week:3, sec:'Zouti Konkrè', icon:'💬',
    title:{kw:'Chatbot — Sistèm 24/7',fr:'Chatbots — Système 24/7',en:'Chatbots — 24/7 systems'},
    lesson:{kw:'Chatbot = asistan otomatik pou biznis. Reponn kestyon, pran kòmand, fè follow-up — 24/7.',
            fr:'Chatbot : assistant business 24/7 — questions, commandes, suivi.',
            en:'Chatbots = automatic business assistants. Answer questions, take orders, follow up — 24/7.'},
    analogy:{kw:'Tankou yon anplwaye ki pa janm mande repo.',
             fr:'Un employé qui ne demande jamais de pause.',
             en:'An employee that never asks for a break.'},
    example:{kw:'Marc nan Pòtoprens enstale chatbot pou 3 restoran. 2 peye $200/mwa = $400 rekiran.',
             fr:'Marc installe des chatbots pour 3 restaurants. 2 payants à 200$/mois = 400$ récurrents.',
             en:'Marc deploys chatbots for 3 restaurants. 2 pay $200/month = $400 recurring.'},
    money:{kw:['Setup $150–$300','Maintenance $50–100/mwa','5 kliyan = revni regilye'],
           fr:['Setup 150–300$','Maintenance 50–100$/mois','5 clients = revenu stable'],
           en:['Setup $150–$300','Maintenance $50–100/mo','5 clients = steady income']},
    quiz:{kw:{q:'Chatbot travay:',a:['Sèlman lajounen','24/7','Sèlman lè ou la','Pa janm'],c:1},
          fr:{q:'Un chatbot travaille :',a:['Le jour','24/7','Quand tu es là','Jamais'],c:1},
          en:{q:'A chatbot works:',a:['Daytime','24/7','When you\'re there','Never'],c:1}} },
  { id:21, week:3, sec:'Zouti Konkrè', icon:'🗂️',
    title:{kw:'Dataset',fr:'Dataset',en:'Dataset'},
    lesson:{kw:'Dataset = koleksyon done AI itilize pou aprann. Moun ki gen done gen pouvwa.',
            fr:'Dataset : collection de données. Qui a les données a le pouvoir.',
            en:'Dataset = a curated collection of data AI learns from. Whoever owns the data has the power.'},
    analogy:{kw:'Tankou liv kontablite pou yon biznis. San liv la, ou pa konnen pwofi ou.',
             fr:'Comme le grand livre comptable d\'une entreprise.',
             en:'Like a business\'s accounting ledger — without it, you don\'t know your profit.'},
    example:{kw:'Lekòl nan Pòtoprens kolekte done nòt elèv. AI ede predi ki moun ki bezwen plis sipò.',
             fr:'Une école collecte les notes : l\'IA prédit qui a besoin de soutien.',
             en:'A school collects student grades — AI predicts who needs extra support.'},
    money:{kw:['Analiz done biznis','Rapò mache','Optimizasyon lavant'],
           fr:['Analyse données','Rapports marché','Optimisation ventes'],
           en:['Business data analysis','Market reports','Sales optimization']},
    quiz:{kw:{q:'Dataset se:',a:['Yon zouti','Koleksyon done','Yon telefòn','Yon AI'],c:1},
          fr:{q:'Un dataset est :',a:['Un outil','Collection données','Un phone','Une IA'],c:1},
          en:{q:'A dataset is:',a:['A tool','Data collection','A phone','An AI'],c:1}} },
  { id:22, week:3, sec:'Zouti Konkrè', icon:'⌨️',
    title:{kw:'Prompt Engineering',fr:'Prompt Engineering',en:'Prompt Engineering'},
    lesson:{kw:'Prompt Engineering = fason ou pale ak AI pou jwenn pi bon rezilta.',
            fr:'L\'art de formuler des requêtes pour obtenir de meilleurs résultats.',
            en:'How you talk to AI to get the best results.'},
    analogy:{kw:'Bay enstriksyon klè nan kwizin: "Fè manje" vs "Fè diri kole ak pwa pou 10 moun".',
             fr:'Instructions cuisine : "Fais à manger" vs "Riz collé aux pois pour 10".',
             en:'Cooking instructions: "Make food" vs "Rice and beans for 10 people, medium spicy".'},
    example:{kw:'"Prompt Pack pou Biznis Ayisyen" vann $27. 100 acha = $2,700.',
             fr:'Un "Prompt Pack Business" à 27$ : 100 ventes = 2700$.',
             en:'A "Business Prompt Pack" at $27 → 100 sales = $2,700.'},
    money:{kw:['Vann prompt pack','Fòmasyon prompt','Konsiltasyon AI'],
           fr:['Prompt packs','Formations','Conseil IA'],
           en:['Sell prompt packs','Prompt training','AI consulting']},
    quiz:{kw:{q:'Pi bon prompt bay:',a:['Pi bon rezilta','Erè','Anyen','Lajan dirèkteman'],c:0},
          fr:{q:'Meilleur prompt =',a:['Meilleur résultat','Erreur','Rien','Argent direct'],c:0},
          en:{q:'Better prompt =',a:['Better result','Error','Nothing','Direct money'],c:0}} },
  { id:23, week:3, sec:'Zouti Konkrè', icon:'🧪',
    title:{kw:'Fòmil bon prompt',fr:'Formule d\'un bon prompt',en:'Good prompt formula'},
    lesson:{kw:'Bon prompt: Wòl + Objektif + Kontèks + Rezilta espere.',
            fr:'Un bon prompt : Rôle + Objectif + Contexte + Résultat attendu.',
            en:'A good prompt: Role + Goal + Context + Expected output.'},
    analogy:{kw:'Detay = presizyon. Plis enfòmasyon ou bay AI, plis rezilta a bon.',
             fr:'Plus de détails, plus de précision.',
             en:'More detail, more precision.'},
    example:{kw:'"Ou se konsiltan maketing pou restoran Ayisyen nan Pétion-Ville. Kreye plan 30 jou."',
             fr:'"Tu es consultant marketing pour un restaurant haïtien à Pétion-Ville. Plan 30 jours."',
             en:'"You\'re a marketing consultant for a Haitian restaurant in Pétion-Ville. Create a 30-day plan."'},
    money:{kw:['Sèvis plan biznis','Stratèji maketing AI','Fòmasyon antreprenè'],
           fr:['Plans business','Stratégie marketing','Formation entrepreneurs'],
           en:['Business plan services','AI marketing strategy','Entrepreneur training']},
    quiz:{kw:{q:'Yon bon prompt gen:',a:['Yon mo','Wòl + objektif + kontèks','Anyen','Imaj'],c:1},
          fr:{q:'Bon prompt =',a:['Un mot','Rôle + obj + contexte','Rien','Image'],c:1},
          en:{q:'Good prompt =',a:['One word','Role + goal + context','Nothing','Image'],c:1}} },
  { id:24, week:3, sec:'Zouti Konkrè', icon:'🧠',
    title:{kw:'LLM — Large Language Model',fr:'LLM — Grand modèle de langage',en:'LLM — Large Language Model'},
    lesson:{kw:'LLM ka ekri, reponn kestyon, analize tèks, tradui. ChatGPT, Claude, Gemini se LLM.',
            fr:'LLM : écrit, répond, analyse, traduit. ChatGPT, Claude, Gemini.',
            en:'LLMs write, answer, analyze, translate. ChatGPT, Claude, Gemini are all LLMs.'},
    analogy:{kw:'Tankou yon gwo bibliyotèk dijital ki li milya paj — epi ou ka pale avè l.',
             fr:'Une bibliothèque géante qui a tout lu et avec qui on parle.',
             en:'A giant library that\'s read billions of pages — and you can talk to it.'},
    example:{kw:'Avoka nan Pòtoprens prepare dokiman pi rapid ak LLM. Sèvis kliyan vin rapid.',
             fr:'Un avocat prépare ses documents plus vite avec un LLM.',
             en:'A Port-au-Prince lawyer drafts documents faster with an LLM.'},
    money:{kw:['Sèvis dokiman legal','Administratif','Fòmasyon pwofesyonèl'],
           fr:['Services juridiques','Administratif','Formation pros'],
           en:['Legal drafting service','Admin services','Pro training']},
    quiz:{kw:{q:'LLM vle di:',a:['Lis Mizik Lokal','Large Language Model','Liv Manyèl','Modèl Pilot'],c:1},
          fr:{q:'LLM signifie :',a:['Lis mu loc','Large Language Model','Livre','Modèle pilote'],c:1},
          en:{q:'LLM stands for:',a:['Local Lab','Large Language Model','Long Loop','Light Lab'],c:1}} },
  { id:25, week:3, sec:'Zouti Konkrè', icon:'💼',
    title:{kw:'Lajan masiv ak AI',fr:'Argent massif avec l\'IA',en:'Massive income with AI'},
    lesson:{kw:'3 nivo: Freelance (vann tan), Ajans (vann ekip), Pwodwi dijital (vann sistèm).',
            fr:'3 niveaux : Freelance, Agence, Produit numérique.',
            en:'3 levels: Freelance (sell time), Agency (sell team), Digital product (sell system).'},
    analogy:{kw:'Travay aktif gen limit. Sistèm otomatik pa gen limit.',
             fr:'Le travail est limité, les systèmes non.',
             en:'Active work has limits. Automated systems don\'t.'},
    example:{kw:'Kou "AI pou Biznis Ayisyen" a $97. 100 moun = $9,700. Plan 90 jou.',
             fr:'Cours "IA Business" à 97$. 100 ventes = 9700$.',
             en:'Course "AI for Haitian Business" at $97 → 100 sales = $9,700.'},
    money:{kw:['Mini-kou','Membership','Ebook','Konsiltasyon AI'],
           fr:['Mini-cours','Abonnements','Ebook','Conseil IA'],
           en:['Mini-courses','Memberships','Ebooks','AI consulting']},
    quiz:{kw:{q:'Pi gwo potansyèl:',a:['Vann tan ou','Vann sistèm','Pa fè anyen','Atann'],c:1},
          fr:{q:'Plus gros potentiel :',a:['Vendre temps','Vendre systèmes','Rien','Attendre'],c:1},
          en:{q:'Biggest upside:',a:['Selling time','Selling systems','Doing nothing','Waiting'],c:1}} },

  // Week 4 — Dominasyon Mache
  { id:26, week:4, sec:'Dominasyon Mache', icon:'💼',
    title:{kw:'AI nan travay',fr:'L\'IA au travail',en:'AI in jobs'},
    lesson:{kw:'AI ap chanje mache travay. Travay repetitif → otomatik. Kreyativite + estrateji → peye plis.',
            fr:'L\'IA change le travail. Le répétitif s\'automatise.',
            en:'AI is reshaping work. Repetitive tasks automate. Creative + strategic work pays more.'},
    analogy:{kw:'Pa chèche sèlman travay. Vin moun ki pote solisyon.',
             fr:'Ne cherchez pas seulement un emploi : apportez des solutions.',
             en:'Don\'t just look for a job — become the person who brings solutions.'},
    example:{kw:'Moun ki metrize AI travay remote pou kliyan entènasyonal, chita lakay yo nan Ayiti.',
             fr:'Maîtriser l\'IA = travailler à distance pour clients internationaux depuis Haïti.',
             en:'Those who master AI work remote for international clients — from home in Haiti.'},
    money:{kw:['Travay remote','Freelance entènasyonal','Vin solisyon'],
           fr:['Travail à distance','Freelance international','Devenir solution'],
           en:['Remote work','International freelance','Become a solution']},
    quiz:{kw:{q:'AI nan travay:',a:['Pa chanje anyen','Chanje mache a','Sèlman risk','Bagay ti moun'],c:1},
          fr:{q:'L\'IA au travail :',a:['Ne change rien','Change le marché','Que risque','Que jeunes'],c:1},
          en:{q:'AI in jobs:',a:['Changes nothing','Reshapes the market','Pure risk','For kids only'],c:1}} },
  { id:27, week:4, sec:'Dominasyon Mache', icon:'📖',
    title:{kw:'AI pou aprann',fr:'L\'IA pour apprendre',en:'AI for learning'},
    lesson:{kw:'AI ka vin pwofesè pèsonèl ou. Maketing, kodaj, angle, biznis — tout an Kreyòl si ou mande l.',
            fr:'L\'IA peut être votre prof personnel — marketing, code, anglais, business.',
            en:'AI can be your personal tutor — marketing, code, English, business. In Creole if you ask.'},
    analogy:{kw:'Si ou itilize AI pou aprann pi vit, ou pran devan moun ki pa itilize li.',
             fr:'Apprendre avec l\'IA = prendre de l\'avance.',
             en:'Learning with AI puts you ahead of those who don\'t.'},
    example:{kw:'Moun nan dyaspora itilize ChatGPT pou aprann Angle an 3 mwa. Jwenn travay $1,200/mwa.',
             fr:'Anglais appris via ChatGPT en 3 mois → job à 1200$/mois.',
             en:'A learner uses ChatGPT to master English in 3 months → $1,200/month remote job.'},
    money:{kw:['Aprann pi vit','Kours gratis AI','Avantaj mache'],
           fr:['Apprendre vite','Cours gratuits','Avantage marché'],
           en:['Learn faster','Free courses with AI','Market advantage']},
    quiz:{kw:{q:'AI ka anseye ou:',a:['Anyen','Anpil bagay','Sèlman jwèt','Pa egziste'],c:1},
          fr:{q:'L\'IA peut t\'apprendre :',a:['Rien','Beaucoup','Que jeux','Inexistant'],c:1},
          en:{q:'AI can teach you:',a:['Nothing','Many things','Only games','Nothing real'],c:1}} },
  { id:28, week:4, sec:'Dominasyon Mache', icon:'🎨',
    title:{kw:'AI pou kreyativite',fr:'L\'IA pour la créativité',en:'AI for creativity'},
    lesson:{kw:'AI pa ranplase kreyativite — li ogmante li. Liv, mizik, podcast, kontni edikatif.',
            fr:'L\'IA n\'efface pas la créativité, elle la décuple.',
            en:'AI doesn\'t replace creativity — it amplifies it. Books, music, podcasts, education.'},
    analogy:{kw:'Kreyativite + AI = pwodwi dijital san limit.',
             fr:'Créativité + IA = produits numériques sans limite.',
             en:'Creativity + AI = digital products without limit.'},
    example:{kw:'Moun ekri liv biznis an Kreyòl ak ChatGPT, vann sou Gumroad. Dyaspora achte anpil.',
             fr:'Un livre business en créole rédigé avec ChatGPT, vendu sur Gumroad à la diaspora.',
             en:'A business book in Creole written with ChatGPT, sold on Gumroad — diaspora buys.'},
    money:{kw:['Liv','Mizik','Podcast','Kontni edikatif','Mache dyaspora'],
           fr:['Livres','Musique','Podcasts','Contenus','Marché diaspora'],
           en:['Books','Music','Podcasts','Education content','Diaspora market']},
    quiz:{kw:{q:'AI ak kreyativite:',a:['Pa konekte','Ranplase','Ogmante','Detui'],c:2},
          fr:{q:'IA et créativité :',a:['Pas liés','Remplacement','Augmentation','Destruction'],c:2},
          en:{q:'AI and creativity:',a:['Unrelated','Replacement','Amplifier','Destroyer'],c:2}} },
  { id:29, week:4, sec:'Dominasyon Mache', icon:'⚠️',
    title:{kw:'Risk yo',fr:'Les risques',en:'The risks'},
    lesson:{kw:'AI gen risk: move enfòmasyon, plajyaris, depandans twòp, pwoblèm etik. Verifye sa AI ba ou.',
            fr:'Risques : désinformation, plagiat, dépendance, éthique. Toujours vérifier.',
            en:'Risks: misinformation, plagiarism, over-dependence, ethics. Always verify what AI gives.'},
    analogy:{kw:'Moun ki sèvi ak AI entelijan ap toujou gen avantaj sou moun ki pa sèvi avè l ak sajès.',
             fr:'Utiliser l\'IA avec sagesse = avantage durable.',
             en:'Using AI wisely is an enduring advantage.'},
    example:{kw:'Toujou verifye enfòmasyon AI ba ou. Kenbe jijman pèsonèl ou. AI se zouti.',
             fr:'Vérifiez toujours, gardez votre jugement.',
             en:'Always verify. Keep your own judgment. AI is a tool, not a replacement for your brain.'},
    money:{kw:['Verifye done','Kenbe jijman','Itilize AI kòm zouti','Etik = repitasyon'],
           fr:['Vérifier','Garder jugement','IA = outil','Éthique = réputation'],
           en:['Verify data','Keep judgment','AI as tool','Ethics = reputation']},
    quiz:{kw:{q:'Pou itilize AI byen:',a:['Pa janm verifye','Toujou verifye','Bliye sèvo w','Suiv san reflechi'],c:1},
          fr:{q:'Bien utiliser l\'IA :',a:['Jamais vérifier','Toujours vérifier','Oublier sa tête','Suivre aveuglément'],c:1},
          en:{q:'Using AI well:',a:['Never verify','Always verify','Ignore yourself','Follow blindly'],c:1}} },
  { id:30, week:4, sec:'Dominasyon Mache', icon:'🇭🇹',
    title:{kw:'Plan Dominasyon Ayiti',fr:'Plan de domination Haïti',en:'Plan to dominate the AI market in Haiti'},
    lesson:{kw:'Pou domine: Niche klè + Prezans rezo sosyal + Pwodwi/sèvis estriktire. Ayiti bezwen lidè dijital.',
            fr:'Niche claire + présence sociale + offre structurée. Haïti a besoin de leaders.',
            en:'Clear niche + social presence + structured offer. Haiti needs digital leaders.'},
    analogy:{kw:'Pa jis itilize AI. Vin referans AI nan Ayiti.',
             fr:'Ne soyez pas utilisateur — devenez la référence.',
             en:'Don\'t just use AI — become THE AI reference in your space.'},
    example:{kw:'Plan 6 mwa: Mwa 1–2 kontni Kreyòl, Mwa 3–4 ofri sèvis, Mwa 5–6 lanse premye pwodwi dijital.',
             fr:'Plan 6 mois : contenu, services, puis produit digital.',
             en:'6-month plan: content → services → digital product launch.'},
    money:{kw:['Mwa 1–2: kontni + odyans','Mwa 3–4: sèvis','Mwa 5–6: pwodwi dijital'],
           fr:['M1–2 contenu','M3–4 services','M5–6 produit'],
           en:['Months 1–2: content + audience','Months 3–4: services','Months 5–6: digital product']},
    quiz:{kw:{q:'Pou domine mache AI Ayiti:',a:['Tann','Klè niche + sèvis','Kopye lòt','Pa anyen'],c:1},
          fr:{q:'Pour dominer l\'IA en Haïti :',a:['Attendre','Niche + services','Copier','Rien'],c:1},
          en:{q:'To dominate AI in Haiti:',a:['Wait','Niche + services + product','Copy','Nothing'],c:1}} },
];
